### ISSUE TITLE
0.10.4 autotest coredump with external htslib 1.9 in bcf_update_format

### ISSUE THREAD

**Issue by smoe** [brentp/cyvcf2#109]
Hello,

for Debian we are inclined to reuse libraries already available in the distribution. And so we fell back on the htslib 1.9 already available. While runnign through the autotests the following happens:

```
...
no intervals found for b'/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test.snpeff.bcf' at 1:69260-69438
ok
cyvcf2.tests.test_reader.test_issue12 ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
Ensure gt_bases works with more complex base representations. ... ok
cyvcf2.tests.test_reader.test_set_format_float ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:567: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([0.555, 1.111], dtype=np.float))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:567: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([0.555, 1.111], dtype=np.float))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:570: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([8.555, 11.111], dtype=np.float64))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:570: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([8.555, 11.111], dtype=np.float64))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:573: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([9998.555, 99911.111], dtype=np.float32))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:573: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([9998.555, 99911.111], dtype=np.float32))
ok
cyvcf2.tests.test_reader.test_set_format_int ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:581: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PI", np.array([5, 1], dtype=np.int))
/home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/tests/test_reader.py:584: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PI", np.array([855, 11], dtype=np.int64))
python3.7: vcf.c:3496: bcf_update_format: Assertion `!fmt->p_free' failed.
Aborted (core dumped)
E: pybuild pybuild:338: test: plugin distutils failed with: exit code=134: cd /home/moeller/git/med-team/cyvcf2/cyvcf2-0.10.4/.pybuild/cpython3_3.7_cyvcf2/build; python3.7 -m nose -v 
dh_auto_test: pybuild --test --test-nose -i python{version} -p 3.7 returned exit code 13
make: *** [debian/rules:12:
```

This looks a bit like as there is a problem with htslib. Can you help with an insight?

The problem was observed both with Python 2 and with Python 3 (3.7).

Cheers,

Steffen

**Comment by daviesrob** [comment]
Judging from the [Travis output](https://travis-ci.org/brentp/cyvcf2/jobs/476959707) it looks like cyvcf2.cpython-37m-x86_64-linux-gnu.so is being built with -DNDEBUG.  This will have turned off assertions, which is why this bug isn't showing up on the normal tests.  It would be advisable to remove this compiler flag if possible.

The bug is being triggered by calling `bcf_update_info()` more than once on the same key, probably during [this test](https://github.com/brentp/cyvcf2/blob/aa32d5d/cyvcf2/tests/test_reader.py#L578).  This points to some missing functionality in htslib - it can't grow the memory region more than once.  The simple solution is to write to different keys, or you could try reordering the tests so the one storing the biggest data item comes first (while should avoid the realloc).  I'm not sure if there is any other work-around, although @pd3 may know better.

**Comment by brentp** [comment]
@smoe I pushed a fix for these tests. I can bump the version if you need that for debian.

**Comment by smoe** [comment]
No bump required. I'll have it as 0.10.4+git2019... . Thank you tons for looking into this so quickly.
Best,
Steffen

**Comment by daviesrob** [comment]
The `DNDEBUG` comes from `python setup.py`.  If you look carefully at your Travis output you'll see that htslib gets built in the way you describe, then `python setup.py` recompiles all the htslib object files using its own set of compiler flags.  In fact, it appears to do this twice - once when running `python setup.py install` and again when running `python setup.py test`.

I haven't done much python extension building, so I'm afraid I'm not sure how to stop this.  One possibility suggested by `pydoc distutils.extension` would be to add an `undef_macros = ['NDEBUG']` attribute to your Extension object in `setup.py` and hope that it adds a `-UNDEBUG` option to the gcc command-line to cancel out the other one.  (I can't easily test this, so I'm just leaving it as a suggestion).

**Comment by brentp** [comment]
@daviesrob thanks again for the diagnosis. I'll try as you suggest.
