### ISSUE TITLE
get a vep/snpeff dict

### ISSUE THREAD

**Issue by moonso** [brentp/cyvcf2#11]
I know this is a bit of a hack but since annotations with vep or snpeff is common I'll give it a go and see what you think.

Would it be possible to create a dictionary(like) structure for variants based on the given annotations mentioned above as default for variants?

Or would it be possible to store the vep/snpeff header in a list in the vcf object like:

``` python
vcf = cyvcf2.VCF("some.vcf")
vcf.VEP_HEADER
> ['Symbol', 'BIOTYPE', ...]
```

?

**Comment by brentp** [comment]
I'll consider, but on first thought, I don't think I want to do that in cyvcf2. 
We do that processing in geneimpacts which is underdocumented, but you can see the usage from the tests: https://github.com/brentp/geneimpacts/blob/master/geneimpacts/tests/test_impacts.py
I think documenting and expanding the functionality there--and perhaps integrating better with cyvcf2-- might be the way to go.
