### ISSUE TITLE
Exception: variant to be written has errorcode: 2

### ISSUE THREAD

**Issue by weber8thomas** [brentp/cyvcf2#110]
Hi,

Thanks for your great work, the tool is really faster than pyvcf !!!
I have an errorcode of type 2 when I want to filter a VCF file to write in another.
```
Traceback (most recent call last):
  File "test_cyvcf2.py", line 47, in <module>
    w.write_record(variant)
  File "cyvcf2/cyvcf2.pyx", line 2087, in cyvcf2.cyvcf2.Writer.write_record
Exception: variant to be written has errorcode: 2
```

When I print the last variant before the crash, I get that : 

`1	13418	.	G	A	510.6	AC_Adj0_Filter	AC=4;AC_AFR=0;AC_AMR=0;AC_Adj=0;AC_EAS=0;AC_FIN=0;AC_Het=0;AC_Hom=0;AC_NFE=0;AC_OTH=0;AC_SAS=0;AF=0.0002073;AN=19292;AN_AFR=108;AN_AMR=8;AN_Adj=752;AN_EAS=52;AN_FIN=2;AN_NFE=138;AN_OTH=14;AN_SAS=430;BaseQRankSum=1.03;ClippingRankSum=-0.358;DP=44639;FS=5.095;GQ_MEAN=7.43;GQ_STDDEV=8.72;Het_AFR=0;Het_AMR=0;Het_EAS=0;Het_FIN=0;Het_NFE=0;Het_OTH=0;Het_SAS=0;Hom_AFR=0;Hom_AMR=0;Hom_EAS=0;Hom_FIN=0;Hom_NFE=0;Hom_OTH=0;Hom_SAS=0;InbreedingCoeff=-0.105;MQ=31.02;MQ0=0;MQRankSum=0.269;NCC=78090;QD=3.67;ReadPosRankSum=0.326;VQSLOD=-1.768;culprit=MQ;DP_HIST=7216|1684|565|127|43|10|1|0|0|0|0|0|0|0|0|0|0|0|0|0,1|2|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0;GQ_HIST=3164|4988|325|244|667|102|76|34|6|11|3|1|23|0|1|0|1|0|0|0,0|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0|0;DOUBLETON_DIST=.;AC_MALE=.;AC_FEMALE=.;AN_MALE=504;AN_FEMALE=248;AC_CONSANGUINEOUS=.;AN_CONSANGUINEOUS=108;Hom_CONSANGUINEOUS=.;AC_POPMAX=NA;AN_POPMAX=NA;POPMAX=NA;K1_RUN=G:0;K2_RUN=GA:1;K3_RUN=GAG:0;ESP_AF_POPMAX=0;ESP_AF_GLOBAL=0;ESP_AC=0;KG_AF_POPMAX=0;KG_AF_GLOBAL=0;KG_AC=0;CSQ=A|downstream_gene_variant|MODIFIER|WASH7P|ENSG00000227232|Transcript|ENST00000438504|unprocessed_pseudogene||||||||||rs75175547|1|945|-1||SNV|1|HGNC|38034|YES||||||||1:g.13418G>A||||||0.03334|0.08697|0.0333|0.02313|0.05618|0.04954|0.009219|0.03791|0.0438|0.08697|gnomAD_AFR||||||1.667|-0.108538||0.54|FALSE|1.667|-0.108538||||||||||||||||||||||||||||0.00120|0.04868||0.2||||||||||||-1.80999994277954|0|-4.70100021362305|0.0784479975700378|||||||,A|non_coding_transcript_exon_variant|MODIFIER|DDX11L1|ENSG00000223972|Transcript|ENST00000456328|processed_transcript|3/3||ENST00000456328.2:n.666G>A||666/1657|||||rs75175547|1||1||SNV|1|HGNC|37102|YES||||||||1:g.13418G>A||||||0.03334|0.08697|0.0333|0.02313|0.05618|0.04954|0.009219|0.03791|0.0438|0.08697|gnomAD_AFR||||||1.667|-0.108538||0.54|FALSE|1.667|-0.108538|n.666G>A|||||||||||||||||||||||||||0.00120|0.04868||0.2||||||||||||-1.80999994277954|0|-4.70100021362305|0.0784479975700378|||||||`

Can you help me with this please ? :)

Thanks !!!

Thomas

**Comment by brentp** [comment]
Hi Thomas, is `AC_Adj0_Filter` defined in the header? 
And/or can you provide small file the will reproduce this error?

**Comment by weber8thomas** [comment]
Yes, it caused the issue. After adding it in the header, there was no problem :)
Thanks !
