### ISSUE TITLE
support for vcf index arg.

### ISSUE THREAD

**Issue by matthdsm** [brentp/cyvcf2#112]
Hi Brent,

Would you see fit to add a `vcf_index` argument? This would be useful in the case where a vcf is hosted on a secure S3 repo, and the file needs to be accessed using a signed URL. This enables the users to add a signed index url for random querying.

Thanks
M

**Comment by matthdsm** [comment]
Alternatively, could you explain how I can change the `idx` attribute of a `VCF` class instance?
I've no experience with Cython, the normal pythonic way doesn't seem to work.

Thanks.
M

**Comment by brentp** [comment]
I'll implement this shortly (next couple of weeks). I just did it in hts-nim yesterday (https://github.com/brentp/hts-nim/commit/44dc67952e7687785f64af217f86b78a6fe3eceb#diff-e3cf75ad8a1f8c68264ea0971daeea77R530)

**Comment by matthdsm** [comment]
Great to hear! Looking forward to it.

Thanks
M

Op 27 feb. 2019 om 15:43 heeft Brent Pedersen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'll implement this shortly (next couple of weeks). I just did it in hts-nim yesterday (brentp/hts-nim@44dc679#diff-e3cf75ad8a1f8c68264ea0971daeea77R530<https://github.com/brentp/hts-nim/commit/44dc67952e7687785f64af217f86b78a6fe3eceb#diff-e3cf75ad8a1f8c68264ea0971daeea77R530>)

**Comment by matthdsm** [comment]
Hi Brent,

I don't mean to rush you, but do you have any idea on a timeline for this?
Thanks
M

**Comment by matthdsm** [comment]
Lovely! Thanks!

Cheers
M

**Comment by brentp** [comment]
this is implemented as `set_index()` in 0.10.9 which is up on pypi.

**Comment by matthdsm** [comment]
Great, thanks again!
M
