### ISSUE TITLE
var_subtype problem as "IndexError: list index out of range"

### ISSUE THREAD

**Issue by rakesh4osdd** [brentp/cyvcf2#115]
Please help in this issue while using VCF information having "monomorphic reference" and checking for its var_subtype.

The error is given below with input information:

1	5875102	167375	T	.	.	.	AF_ESP=0.84313;AF_EXAC=0.83625;AF_TGP=0.84325;ALLELEID=177885;CLNDISDB=MedGen:CN169374;CLNDN=not_specified;CLNHGVS=NC_000001.11:g.5875102T%3D;CLNREVSTAT=criteria_provided,_single_submitter;CLNSIG=Benign;CLNVC=single_nucleotide_variant;CLNVCSO=SO:0001483;CLNVI=HGMD:CS057899;GENEINFO=NPHP4:261734;MC=SO:0001574|splice_acceptor_variant;ORIGIN=1;RS=1217117155|1287637

IndexErrorTraceback (most recent call last)
<ipython-input-33-618534bee4d1> in <module>()
     12             nsnp = nsnp +1
     13             print(variant)
---> 14             print(variant.var_subtype)
     15 #             if(variant.var_subtype=='ts'): # transition
     16 #                 ts=ts+1

/home/rakesh/anaconda2/lib/python2.7/site-packages/cyvcf2/cyvcf2.pyx in cyvcf2.cyvcf2.Variant.var_subtype.__get__()
   1663         def __get__(self):
   1664             if self.is_snp:
-> 1665                 if self.is_transition:
   1666                     return "ts"
   1667                 if len(self.ALT) == 1:

/home/rakesh/anaconda2/lib/python2.7/site-packages/cyvcf2/cyvcf2.pyx in cyvcf2.cyvcf2.Variant.is_transition.__get__()
   1614             ref = self.REF
   1615                 # just one alt allele
-> 1616             alt_allele = self.ALT[0]
   1617             if ((ref == 'A' and alt_allele == 'G') or
   1618                 (ref == 'G' and alt_allele == 'A') or

IndexError: list index out of range

**Comment by brentp** [comment]
thanks for reporting. this is fixed in cyvcf2 v0.10.10 which has been uploaded to pypi.
