### ISSUE TITLE
Initialization of Writer class throws `Segmentation fault`

### ISSUE THREAD

**Issue by MuhammedHasan** [brentp/cyvcf2#117]
My vcf file:
```
##fileformat=VCFv4.0
##phasing=partial
##contig=<ID=1,length=16>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA00001	NA00002	NA00003
chr1	4	.	T	C	9.6	.	.	GT:HQ	./.:51,51	0|0:51,51	1/1:51,51
chr1	5	.	A	GA	10	.	.	GT:HQ	0|0:10,10	0|0:10,10	0|0:3,3
chr1	25	.	AACG	GA	10	.	.	GT:HQ	0|0:10,10	1/1:10,10	0|0:3,3
```

My code:
```
vcf = cyvcf2.VCF(vcf_path)
writer = cyvcf2.Writer(output_vcf_path, vcf)
```

Initialization of Writer class throws `Segmentation fault`. I don't know what is wrong but at least it should not throw `Segmentation fault` error but more meaningful error message.

**Comment by brentp** [comment]
this does not segfault for me. can you update to latest version and retry? if it does segfault, I'll need the exact code that recreates. I added a test using your example VCF and code and it passes without problem.

**Comment by MuhammedHasan** [comment]
Updating cyvcf2 solved the problem. Sorry for a false alarm.
