### ISSUE TITLE
Reading from GCS

### ISSUE THREAD

**Issue by FaizShah** [brentp/cyvcf2#119]
Hi all,

What is the recommended way to read a private VCF file from GCS? Anyone gotten this working before (or with s3)?

I just did an:

```python
from cyvcf2 import VCF

vcf = VCF('gs://my-bucket/myfile.vcf')
```

And got the error:

```
OSError: Error opening b'gs://my-bucket/myfile.vcf'
```

I did `gcloud auth login` before running this, as usual, and htslib seems to properly get the token from the default environment variable: https://github.com/samtools/htslib/blob/9cd85ab512a74fe42af31fc6321c70203d161ed6/hfile_gcs.c#L75

I was going to use [GCSFS](https://github.com/dask/gcsfs) which lets you interact with GCS as if it's a local FS in python. But cyvcf2 wants a file location (I think it passes this on to htslib?) not a File object.

So I read the similar issue, #96, which seems to suggest building htslib from source with GCS could solve the issue but looking at the htslib docs seems to suggest it is installed by default now.

Any ideas?

**Comment by brentp** [comment]
you'll probably have to adjust the setup.py in cyvcf2 to support libcurl with google cloud support.
I'd like to support this better, but I don't have the knowledge/time to get the install working for that use-case. It'd be great to get someone to contribute that.

**Comment by FaizShah** [comment]
Ok let me have a look! :)

I just found a similar issue from pysam: https://github.com/pysam-developers/pysam/issues/592

> !export HTSLIB_CONFIGURE_OPTIONS="--enable-gcs"
> !apt-get install libbz2-dev libcurl4-openssl-dev
> !pip3 install pysam -v --force-reinstall --no-binary :all:

Seems to suggest something like this might work.

**Comment by brentp** [comment]
yes, now you just need to make the setup.py respect `HTSLIB_CONFIGURE_OPTIONS`. :)

**Comment by FaizShah** [comment]
Closing this issue for now, I have looked more deeply into this and tried using PySam as well. There is some non-standard env variable called GCS_AUTH_TOKEN in HTSLIB that is used to authenticate reading from gcs that I am currently struggling to get working across pysam and cyvcf2.
