### ISSUE TITLE
Accessing Format Fields

### ISSUE THREAD

**Issue by NoSeatbelts** [brentp/cyvcf2#12]
Hi,

Is there a way to access format fields through this? I decided to try using this over pysam because they currently don't support it.

I thought that perhaps the format method would work, so I tried it on a VCF produced by a simple pileup-like tool.

I have it segfault when given `b.format(key, int)`, where key is any of my integer keys, even though the VCF is produced by htslib and seems valid.

"1\t11167450\t.\tA\tG,T\t0\t.\t.\tADP_ALL:ADP_PASS:ADPD:ADPO:ADPR:AFR:BMF_PASS:BMF_QUANT:FA_FAILED:FM_FAILED:FR_FAILED:PV_FAILED:QSS:RVF:AMBIG:OVERLAP\t755,2,1:588,0,1:231,0,0:360,0,0:415,0,0:0.996042,0.00263852,0.00131926:1,0,0:754,2,1:68,1,0:167,2,0:1,0,0:0,0,0:1280022,0,3077:0.549669,0,0:3:441"

Am I querying this incorrectly?

**Comment by brentp** [comment]
Can you share a subset of the vcf that causes the segfault?

**Comment by NoSeatbelts** [comment]
[chr7.COLO928.vcf.txt](https://github.com/brentp/cyvcf2/files/309491/chr7.COLO928.vcf.txt)

It segfaults on accessing float fields as well.

Now, this is from the pip build. Should I be building from source?

**Comment by brentp** [comment]
I can recreate with that VCF. The problem is the ones that have Number=R. I'll see if I can fix.

**Comment by NoSeatbelts** [comment]
Thanks for checking it out!

Can you try OVERLAP? That one also segfaulted for me, and it has Number=1 rather than R.

**Comment by brentp** [comment]
@NoSeatbelts thanks for the great test-case. I fixed this and added part of your VCF as a test. I wasn't intializing my variable:
https://github.com/brentp/cyvcf2/commit/ee2539e53ba0da0d83613b1b28aac87e095180b3#diff-d2e3efc243dbc6091801ff7218ebabfdR875

please pull from git and let me know if you have any more problems.

**Comment by NoSeatbelts** [comment]
Great work. Thanks! I'll check it out.

It'll be a lot faster (and cleaner) than my hacked-together `fmt_dict = {k, v for k, v in zip(str(b).split("\t")[8].split(":"), str(b).split("\t")[9].split(":")}`, with manual subfield splitting!

**Comment by brentp** [comment]
Yes, should be much faster than that. I'm currently making a copy of the data instead of just a numpy view. If I did the view, it'd be even faster.

**Comment by NoSeatbelts** [comment]
Typed memory views are awesome. I never figured out how to do them properly when I was still writing cython.
