### ISSUE TITLE
Accessing seqlens property causes segmentation fault

### ISSUE THREAD

**Issue by VidJa** [brentp/cyvcf2#120]
I'm trying something along the line:
```
from cyvcf2 import VCF
bcf_obj = VCF('bcf_file.bcf')
seqnames = bcf_obj.seqnames
seqlens = bcf_obj.seqlens
chromosome_dict = dict(zip(seqnames, seqlens))
```

requesting the seqlens property to get the list of chromosome lengths from the VCF file results in python to segfault if the header does not contain the lengths:

returning an exception would be great for wrapping in the seqlens call in a try statement

example (from freebayes generated VCF, crashes python): 
##contig=<ID=Chr_01>
##contig=<ID=Chr_02>
##contig=<ID=Chr_03>

instead of (from GATK generated VCF, just fine):
##contig=<ID=Chr_02,length=236873709>
##contig=<ID=Chr_03,length=216989777>
##contig=<ID=Chr_04,length=168230252>

**Comment by brentp** [comment]
this is fixed now in v0.11.4. It will raise an AtttributeError
thanks for the clear report.
