### ISSUE TITLE
Missing input data for test suite

### ISSUE THREAD

**Issue by tillea** [brentp/cyvcf2#124]
Hi,
the file cyvcf2/tests/test_reader.py contains test test_117 that tries to load the file test.bug.117.vcf.  This file is not part of the download tarball.  It would be nice if you could include this file in the next version.
Kind regards, Andreas.

**Comment by brentp** [comment]
added, tagged 0.11.5 and pushed. thanks for letting me know.

**Comment by tillea** [comment]
On Thu, Aug 01, 2019 at 06:14:18AM -0700, Brent Pedersen wrote:
> added, tagged 0.11.5 and pushed. thanks for letting me know.

Thanks a lot, uploaded to Debian, Andreas.
