### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by jdelafon** [brentp/cyvcf2#13]
When trying to install this package with pip3, one gets an error message: "cyvcf2 is only for python 2.7". 
I am interesting to port it to Python3. Have you already tried ? Was there any special difficulty ? Usually there are very few changes to make, and work has already been done in this direction (there is a PY_MAJOR_VERSION < 3 check for strings encoding).

This is in order to have vcf2db usable in modern Python programs.

**Comment by brentp** [comment]
I did have a look at this, but got lost in what I needed to do inside the cython code. I would very much welcome a pull-request that added python3 support and will help as I can.

**Comment by jdelafon** [comment]
Ok I will give it a try. Because I have to justify my work, is there any way that you can save me some pain by telling me why not to use the older PyVCF instead ? Is there a benchmark somewhere ? I saw that you and Aaron contributed to it.

**Comment by brentp** [comment]
I just did a quick test using this cyvcf2 code:
```
from cyvcf2 import VCF
import sys

for i in range(100):
    for v in VCF(sys.argv[1]):
        v.CHROM, v.start, v.gt_types, v.gt_ref_depths, v.gt_alt_depths, v.gt_bases
```

and this pyvcf code:

```
from vcf import Reader as VCF
import sys

for i in range(100):
    for v in VCF(open(sys.argv[1])):
        gts = v.samples
        v.CHROM, v.POS, gts
```

and ran both of those on cyvcf2/tests/test-haploidX.vcf since that's the largest test file in the cyvcf2 tests.

On my machine, the user time for pyvcf is 8 seconds and for cyvcf2, it is 0.95 seconds, so it is over 8 times faster. The difference will be larger for VCF's with larger numbers of samples. 

Also note that this is somewhat unfair to cyvcf2 as cyvcf2 does more work to make them into numpy arrays. It also uses the parser from htslib, so any VCF that htslib supports will be available to cyvcf2. 

An additional benefit is that cyvcf2 supports BCF.

**Comment by jdelafon** [comment]
Nice, thanks ! This could be worth adding to the readme.
Also pyvcf says it only has "partial" support for vcf4.2, whatever that means.

**Comment by brentp** [comment]
I just pushed to a branch that supports python3 with all tests passing on python3.5 and python2.7

https://travis-ci.org/brentp/cyvcf2/jobs/143457510

would be great if you could try it out and let me know any problems. Could be some missing test-cases for stuff but I can fix quickly now.

**Comment by jdelafon** [comment]
Tests pass for me, too (Python 3.4). We'll see if something is missing when used by vcf2db (which I will port to Python3 - no C code debugging this time). If I see something I'll send test cases in a pull request.

**Comment by brentp** [comment]
for the port, most of the "work" is in the addtion of the to_bytes() function that handles receiving bytes or not from python3.

**Comment by jdelafon** [comment]
One problem that I could see, is that the `v.INFO`, where `v` is a `cyvcf2.Variant`, has all its keys as bytes in the Python3 version. This greatly messes up with code in vcf2db, because at some point this `v.INFO` is merged with other properties with new string keys. The rest of the code expects these new keys as strings for comparisons (in like a hundred places), including what is passed to geneimpacts, so I think it is wiser to make cyvcf2 return strings instead in that dict.

**Comment by brentp** [comment]
I pushed a change that makes most stuff strings including REF, ALT, CHROM and dict stuff.
