### ISSUE TITLE
int32 overflow?

### ISSUE THREAD

**Issue by Hoeze** [brentp/cyvcf2#133]
Hi, is this library type-safe?

I just tried to fetch variants in an interval "22:0-np.iinfo("int").max" and got an empty list.
Instead, "22:0-np.iinfo("int32").max" was working.

However, I did not get any warning message about some possible integer overflow, etc.

**Comment by brentp** [comment]
can you provide a test-case? this uses htslib < 1.10 which only used 32 bits for integer positions. as of about 2 months ago, htslib position is 64 bits, but I haven't updated to that.

**Comment by grahamgower** [comment]
cyvcf2 is now using htslib >= 1.10, so this should be fixed. In any event, I can't reproduce this.
