### ISSUE TITLE
support for pVCF? 

### ISSUE THREAD

**Issue by aderzelle** [brentp/cyvcf2#135]
Hello,
I am looking for a way to parse a GLnexus pVCF, I used to use R for vcf parsing but so far it's not clear to me it is handling the pVCF correctly (I opened a thread about it here: https://github.com/knausb/vcfR/issues/152). Have you had any experienced of pVCF witg cyvcf2? 

Here is how it looks like 

```
##contig=<ID=chromosome_34,length=44>
##contig=<ID=chromosome_35,length=43>
##bcftools_viewVersion=1.9+htslib-1.9
##bcftools_viewCommand=view ALL.nexus.bcf; Date=Thu Feb 20 09:32:56 2020
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	ancestor	D2A1	D2B3	D3A1	D4A3	D5B3	H2A3	H2C3	H4A4	H4C2	H5A3
chromosome_1	6340194	chromosome_1_6340194_G_C	G	C	43	.	AF=0.454545;AQ=43	GT:DP:AD:GQ:PL:RNC	0/1:301:164,132:31:31,0,40:..	./.:.:.:.:0,0,0:MM	0/1:43:26,17:37:37,0,56:..	0/1:45:23,22:34:35,0,38:..	0/1:55:24,31:34:33,0,53:..	0/1:82:41,41:26:26,0,42:..	0/1:44:33,11:27:27,0,49:..	0/1:134:82,52:34:34,0,48:..	0/1:49:34,15:34:33,0,59:..	0/1:211:118,92:43:43,0,56:..	0/1:201:102,99:41:41,0,56:..
```
To give you an idea, I would like to query to get de novo mutation unique per sample (so I must check the mutation is neither in the ancestor nor other samples), among other things

As vcf format can be tricky, I don't rely on the fact I can read the file or that it might "seem" to work, I fear some cases could manifest and break things.  

Thank you

EDIT: actually I can't do a simple query like in the example 

```
from cyvcf2 import VCF
vcf = VCF('/home/alessandro/Data/18-02-2020_DeepVariant/ARCcestor_mosquito_model/ALL.nexus.vcf.gz')
for v in vcf:
    if v.INFO["AF"] > 0.1: continue
    print(str(v))
```
This returns

`TypeError: '>' not supported between instances of 'tuple' and 'float'
`

**Comment by brentp** [comment]
that error means your AF field is a tuple so you can check `v.INFO["AF"][0] > 0.1`
the example variant you pasted looks like a regular vcf and so you should be able to parse it with cyvcf2, if it's not a valid VCF, then you will not be able to.

**Comment by aderzelle** [comment]
Simple enough
thank you!
