### ISSUE TITLE
Ubuntu:18.04 Undefined symbol: aaf

### ISSUE THREAD

**Issue by NickEngland** [brentp/cyvcf2#137]
I've got a strange error when I try to import cyvcf2. I get:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import cyvcf2
  File "/usr/local/lib/python2.7/dist-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /usr/local/lib/python2.7/dist-packages/cyvcf2/cyvcf2.so: undefined symbol: aaf
```

If I use debian-buster instead then I don't get the error.

Minimal Dockerfile which works:
```
FROM python:2.7.17-slim-buster

WORKDIR /opt/example
RUN apt-get update && apt-get install -y \
  build-essential \
  libbz2-dev \
  libcurl4-openssl-dev \
  liblzma-dev \
  libssl-dev \
  lzma-dev 

RUN pip install cyvcf2
RUN echo "import cyvcf2" > test.py
RUN python test.py
```

Minimal Dockerfile which fails:

```
FROM ubuntu:18.04

WORKDIR /opt/example
RUN apt-get update && apt-get install -y \
  build-essential \
  libbz2-dev \
  libcurl4-openssl-dev \
  liblzma-dev \
  libssl-dev \
  lzma-dev \
  python \
  python-pip

RUN pip install cyvcf2
RUN echo "import cyvcf2" > test.py
RUN python test.py
```

Any ideas why this is happening?

**Comment by NickEngland** [comment]
If I remove the keyword "inline" from both aaf and ab_ok then compile it with pip install -e . then I get it working on Ubuntu:18.04!

**Comment by brentp** [comment]
hmm. would you make a PR to that effect?

**Comment by brentp** [comment]
would you try the inline-fix branch? I updated it to use "static inline" and it changes travis to test on bionic and on python 3.8 and all seems ok.

**Comment by brentp** [comment]
sorry for waiting to do this til you'd already fixed it yourself, didn't see a solution til I got in to try it out.

**Comment by NickEngland** [comment]
Inline-fix works for me too on Ubuntu18.04 python2.7. :)

I don't understand why inline produces different behavior on Bioinic to buster though!

**Comment by brentp** [comment]
/shrug . supporting python2, python3, * clang, gcc * various distros is always entertaining.
