### ISSUE TITLE
Get wrong information about read depths

### ISSUE THREAD

**Issue by wavefancy** [brentp/cyvcf2#153]
Dear Developers,

I have a VCF ([LINK here](https://www.dropbox.com/s/tfiuq1yfymfa9bz/QC.EH_LCR_SEGDUP_GQ_DP_MRR_MISSING.chrM.vcf.gz?dl=0)) as attached. When I use 
```
        dp = variant.gt_depths
        rdp = variant.gt_ref_depths
        adp = variant.gt_alt_depths
```
to extract the depth information. However, I got totally wrong information. 
Like the output as below:
```
[11 10 10 ... 10 10 10]
[11 -1 -1 ... -1 -1 -1]
[-1 10 10 ... 10 10 10]
```
The first recode actually like this: ` GT:AD:DP:GQ:PGT:PID:SB  1/1:11,2316,0,0,0,0,0,0,0,0:2327:99:.:.:9,2,1245,1071`

So the ref should 11, alt dp 2316. Total DP 11 + 2316.

Can you please help with this?

Thank you very much!

Best regards
Wallace

**Comment by brentp** [comment]
Hi, the `gt_` fields only work for bi-allelic variants.

**Comment by wavefancy** [comment]
Hi @brentp ,

Thanks much for your quick response. If so, do you have a workaround suggestion here if I have to deal with multiple-allelic sites?

Best regards
Wallace

**Comment by brentp** [comment]
for example, you can use, e.g. `depths = variant.format('AD')` and that will give you a numpy array of shape (n_samples, n_alts+1) so you can take the row-sums to get the depths. You can use `depths[:, 0]` to get ref_depths, an so on.

**Comment by wavefancy** [comment]
Oh, this is great. 

I found this project is great, very flexible and very fast.  By the way, could you please remind me any other functions I would aware only support bi-allelic sites?  I didn't find those info in the documents. I mainly used to fetch genotypes and reads depths. Does the genotypes handles good for multiple allelic sites? 

But I would suggest make notes in the documents for reminding users if you have time. 

Thanks so much though. 

Best regards 
Wallace

**Comment by brentp** [comment]
pull-requests to improve the docs are always welcome. you can use .genotypes to get the genotypes for multi-allelic sites.

**Comment by wavefancy** [comment]
Great, thanks so much! - Wallace
