### ISSUE TITLE
Incorrect variants returned for first few iterations when skipping into file

### ISSUE THREAD

**Issue by hyanwong** [brentp/cyvcf2#155]
In the standard 1000 genomes vcf from http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz with its associated tbi file in the same location, cyvcf2 seems to return the wrong variants when reading starting at a non-zero location in the file. For instance, starting at position 20214740, the first 2 variants returned are both less than 20214740 and have a strange alt allele, listed as `<CN2>`:

```
>>> import cyvcf2
>>> cyvcf2.__version__
'0.20.1'
>>> g = cyvcf2.VCF("ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz")("20:20214740-21875477")
>>> next(g)  # BAD
Variant(20:20172060 A/<CN2>)
>>> next(g)  # BAD
Variant(20:20172424 C/<CN2>)
>>> next(g)
Variant(20:20214740 A/G)
```

In fact, I can't find a variant at position 20172060 at all. This is cyvcf2 on linux (CentOS), Python 3.7.6 | packaged by conda-forge, installed via pip : `pip install cyvcf2), with HTSlib 1.10.2:

```
conda list htslib
# packages in environment at /users/mcvean/yanwong/miniconda3:
#
# Name                    Version                   Build  Channel
htslib                    1.10.2               hd3b49d5_1    bioconda
```

The same file read by scikit-allel does not have this problem, as far as I can tell.

**Comment by brentp** [comment]
This is the correct behavior. It's also visible with bcftools:
```
bcftools view -H http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz 20:20214740-21875477 | head -5 | cut -f 1-5
```
The 2 variants you label as `BAD` have END's that extend into your query range.

**Comment by hyanwong** [comment]
AH - thank you. Apologies for the noise.
