### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [brentp/cyvcf2#158]
Hi there,

I think I've found a memory leak in `cyvcf2`.

With the simple script
```
#!/bin/env python3

import cyvcf2
from memory_profiler import profile

@profile
def main():
    vcf_floc = ...
    vcf = cyvcf2.VCF(vcf_floc)
    for locus in vcf:
        locus.genotype.array()
        
if __name__ == "__main__":
    main()
```

I get the following memory graph:
![image](https://user-images.githubusercontent.com/1317013/89481008-a771e600-d74b-11ea-9525-03bc36308ada.png)

Just to compare, this example that doesn't use cyvcv2 doesn't have the issue:
```
#!/bin/env python3

from memory_profiler import profile

@profile
def main():
    while True:
        a = ['a'] * 250000

if __name__ == "__main__":
    main()
```
![image](https://user-images.githubusercontent.com/1317013/89481163-046d9c00-d74c-11ea-9d8a-32beed0b5ce3.png)

Any ideas?

**Comment by brentp** [comment]
yes. i see the problem. should have a fix tomorrow.

**Comment by LiterallyUniqueLogin** [comment]
Thanks so much for the fast response!

**Comment by brentp** [comment]
Actually, this was pretty easy to fix and should be faster now too. I tagged v0.20.4, pushed it to pypi and it should be available on bioconda soon.
thanks for reporting and plotting.

**Comment by LiterallyUniqueLogin** [comment]
At first blush, the fix seems to be working for me. Thank you!
