### ISSUE TITLE
Genotype representation chromosome X and Y in male sample

### ISSUE THREAD

**Issue by tomiles** [brentp/cyvcf2#159]
The content of variant.**gt_types** doesn't seem to match what I expect.

**Example vcf** (with samples A=male, B=male, C=female):
```
##fileformat=VCFv4.2
##contig=<ID=chrX,length=156040895>
##INFO=<ID=AC,Number=1,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">
##INFO=<ID=AF,Number=1,Type=Float,Description="Allele Frequency, for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block">
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.">
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	A	B	C
chrX	129558701	.	C	A	2799.4	PASS	AC=2;AF=0.5;AN=4	GT:AD:DP:GQ:PL	1:0,56:56:99:1748,0	0:19,0:19:99:0,697	0/1:74,41:115:99:1083,0,2015
```

**Observed output** when parsing with cyvcf2:
```python
>>> vcf = VCF('test.vcf')
>>> for v in vcf():
...     print(str(v))
...     print(str(v.gt_bases))
...     print(str(v.gt_types))
...     print(v.genotypes)
... 
chrX	129558701	.	C	A	2799.4	PASS	AC=2;AF=0.5;AN=4	GT:AD:DP:GQ:PL	1:0,56:56:99:1748,0	0:19,0:19:99:0,697	0/1:74,41:115:99:1083,0,2015

['A' 'C' 'C/A']
[1 0 1]
[[1, True], [0, True], [0, 1, False]]

```
The constants are defined as:
HOM_REF = 0
HET = 1
UNKNOWN = 2
HOM_ALT = 3

So in the case of haploid calls I would expect the v.gt_types output to be: `[3 0 1]` where the first male sample should have type HOM_ALT instead of HET since there is only one allele for this sample.

My expected output seems to match how arq5x/cyvcf parses the alleles to generate the gt_types:
https://github.com/arq5x/cyvcf/blob/f58860dd06b215b9d9ae80e2b46337fb6ab59139/cyvcf/parser.pyx#L260-L272
```python 
               if len(self.alleles) == 2:
                    if self.alleles[0] == self.alleles[1]:
                        if self.alleles[0] == "0":
                            gt_type = HOM_REF
                        else:
                            gt_type = HOM_ALT
                    else:
                        gt_type = HET
                elif len(self.alleles) == 1:
                    if self.alleles[0] == "0":
                        gt_type = HOM_REF
                    else:
                        gt_type = HOM_ALT
```

Do I have the wrong expectation or is this just an edge-case that is not yet handled in cyvcf2?
(as a workaround in my code I currently just use the gt_bases value to generate gt_types myself the way arq5x/cyvcf does)

**Comment by brentp** [comment]
I think this is just a convenient mis-use of terminology (for HOM_REF, HET, etc) in cyvcf2. 
If you open the vcf with `gts012=True`, then you can instead think of the number returned from gt_types as the number of alt alleles which matches HOM_REF=0, HET=1, HOM_ALT=2 (and UNKNOWN=3) for a diploid, but is still understandable for haploid.

You can also use the .genotypes attribute to get finer access to genotypes.

**Comment by tomiles** [comment]
This does complicate downstream analysis, like when we convert the vcf to a gemini db (which uses cyvcf2) then gt_types and  num_hom_ref, num_hom_alt, num_het don't make sense and require a workaround to be able to do useful queries based on this info like when querying variants based on inheritance patterns in a trio when the variant is on X or Y in a male sample.

So shouldn't this be fixed at the cyvcf2 level like arq5x/cyvcf does it? or am I misunderstanding you explanation.

**Comment by brentp** [comment]
gemini will only work with diploid (called) samples. If you add haploid calls from the sex chroms to gemini, it will not work as expected. 
cyvcf2 gives you the means to access the exact calls so you can use those if you need them.

if you are hitting limitations of gemini, you can switch to its successor, [slivar](https://github.com/brentp/slivar) which uses sample.alts as a count of the number of alternate alleles.
