### ISSUE TITLE
Changing genotypes during writing

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [brentp/cyvcf2#165]
Hi there,

I'm implementing a VCF filtering library on top of cyvcf2. During filtering at a record I'd like to modify that record by setting the genotypes of any samples which have been filtered to no calls ([-1]*ploidy). What is the correct way to do that? I don't see an example of modifying the genotype in the docs.

Thanks,

Jonathan

**Comment by brentp** [comment]
Hi, you can see how to set genotypes from the tests here: https://github.com/brentp/cyvcf2/blob/master/cyvcf2/tests/test_reader.py#L672

**Comment by LiterallyUniqueLogin** [comment]
Okay, that seems to work. May I submit a PR adding docs to [this page](https://brentp.github.io/cyvcf2/#modifying-existing-records) with that information?

**Comment by LiterallyUniqueLogin** [comment]
I just realized that cyvcf2 does not support the writing of string format fields as discussed in [this preexisting issue](https://github.com/brentp/cyvcf2/issues/59). That's something I'd need in order to adopt cyvcf2. I've commented there if you're willing to continue the conversation in that thread.

**Comment by brentp** [comment]
yes, please open a PR for docs, and i'll follow the discussion in the other issue.

**Comment by LiterallyUniqueLogin** [comment]
PR is [here](https://github.com/brentp/cyvcf2/pull/166)

**Comment by LiterallyUniqueLogin** [comment]
The PR was accepted, so this can be closed if you'd like.
