### ISSUE TITLE
Set CHROM

### ISSUE THREAD

**Issue by mbhall88** [brentp/cyvcf2#167]
It would be useful to be able to set `CHROM`

I tried implementing a `set_chrom` method on `Variant` similar to `set_pos` but it keeps saying `AttributeError: 'cyvcf2.cyvcf2.Variant' object has no attribute 'set_chrom'`

```py
    def set_chrom(self, chrom):
        """
        set CHROM for the variant
        """
        self.b.rid = chrom
```

Excuse my naivety as I've not worked with cython code before so I assume I'm missing something here...

**Comment by brentp** [comment]
It won't work exactly like that because `rid` is the integer reference id. I'll see about implementing this next week.
You need to do: `CYTHONIZE=1 python setup.py test` to get a new build after each change.
