### ISSUE TITLE
Support mixed-ploidy data in Genotypes.array()

### ISSUE THREAD

**Issue by timothymillar** [brentp/cyvcf2#169]
Hi there, thanks for cyvcf2!

I'm working with mixed ploidy data and notice that Genotypes.array() is treating a lower ploidy genotype as a partial genotype of higher ploidy.
For example a VCF record in which only the second sample is diploid:
```
CHR1	7	.	A	C	60	PASS	NS=3	GT	0/0/1/1	0/1	0/1/./.
```

results in the array:
```python
>>> record.genotype.array()
array([[ 0,  0,  1,  1,  0],
       [ 0,  1, -1, -1,  0],
       [ 0,  1, -1, -1,  0]], dtype=int16)
```
where the diploid and partial tetraploid calls are indistinguishable.

The cause is the end-of-vector value being processed and then overflowing to `-1`
```python
>>> raw = int.from_bytes(b'\x80\x00\x00\x01', 'big', signed=True)
>>> array = np.zeros(1, dtype=np.int16)
>>> array[0] = (raw >> 1) - 1
>>> array
array([-1], dtype=int16)
``` 

The simplest way to avoid this is to check for `bcf_int32_vector_end` and replace it with a sensible alternative such as `-2`:
```python
    def array_mixed(Genotypes self):
        ...
        for ind in range(self.n_samples):
            for allele in range(self.ploidy):
                raw = self._raw[ind * self.ploidy + allele]
                if raw == bcf_int32_vector_end:
                    to_return[ind, allele] = -2  # indicate non-allele
                else:
                    to_return[ind, allele] = (raw >> 1) - 1
            to_return[ind, self.ploidy] = (self._raw[ind * self.ploidy + 1] & 1) == 1

        return to_return
```

resulting in the array
```python
array([[ 0,  0,  1,  1,  0],
       [ 0,  1, -2, -2,  0],
       [ 0,  1, -1, -1,  0]], dtype=int16)
```

If there is a need to preserve the current behavior then a `fill` argument could be added which defaults to `-1`.

Would you be happy to receive a PR for this?

**Comment by brentp** [comment]
Yes, please open a PR. Thanks for reporting!
