### ISSUE TITLE
Associating sample names to genotypes.

### ISSUE THREAD

**Issue by karlpetri** [brentp/cyvcf2#170]
Thank you so much for cyvcf2!!
Amazing tool!!
Quick question: 
I am trying to associate genotypes to sample names.

Will the order of genotypes given by 'variant.genotypes' be the same as the order of samples given by 'VCF.sample' so I could just zip the two lists or is there a smarter way to do an association like this?

Thank you so much for your help!!
-Karl

**Comment by brentp** [comment]
Glad it's useful. Yes, you can do, e.g.:

```Python
sample_to_idx = {s: i for i, s in enumerate(vcf.samples)}
idx_to_sample =  {i, s for i, s in enumerate(vcf.samples)}
```
and then use those as lookups.

**Comment by karlpetri** [comment]
Amazing. Thanks for the swift response. So is it correct to say that the order of the samples and the variant.genotypes list is always the same e.g. if three samples were returned by vcf.samples:
['HGX', 'HGY', 'HGZ']
and three genotypes by variant.genotypes e.g.:
[[0, 1, True],[1, 0, True],[0, 0, True]]
would the following association always be true?:
'HGX' has genotype [0, 1, True]
'HGY' has genotype [1, 0, True]
'HGZ' has genotype [0, 0, True]

**Comment by brentp** [comment]
yes. that's correct.

**Comment by karlpetri** [comment]
Thank you so much!
