### ISSUE TITLE
Translating code from pysam to cyvcf2

### ISSUE THREAD

**Issue by alanwilter** [brentp/cyvcf2#176]
Hi there, since I finally got `cyvcf2` working, now I'm facing how to convert a critical piece of python code from `pysam`.

Essentially I have a VCF with 5M variants (rows) and 8K samples (cols)

The aim of my code is, for a given querying variant, to go and get the row and all data samples and return a dict.

```python
# pysam snippet
variant_file = VariantFile(vcf_file, index_filename=vcf_index)
v = next(variant_file.fetch(chrom, pos - 1, pos))
variant_dict["genotypes"] = [
    {
        "sample": [{"display": phenoid_mapping.get(s)}],
        "GT": v.samples[s].get("GT", ""),
        "AD": v.samples[s].get("AD", ""),
        "DP": v.samples[s].get("DP", ""),
    }
    for s in v.samples
]
```
Now, with `cyvcf2`, after reading the API doc and some guessing, the closest I got (not fully working, bloody slow):
```python
variant_file = VCF("s3://3kricegenome/test/test.vcf.gz") # this is an public example, not my private VCF
v = next(variant_file(f"{chrom}:{pos}-{pos}"))
variant_dict["genotypes"] = [
    {
        "sample": [{"display": phenoid_mapping.get(s)}],
        "GT": v.genotypes[variant_file.samples.index(s)][:2],
        "AD": (v.gt_ref_depths[variant_file.samples.index(s)], v.gt_depths[variant_file.samples.index(s)]),
        "DP": v.gt_depths[variant_file.samples.index(s)],
    }
    for s in variant_file.samples
]
```
My first attempt is very inefficient, so I'm wondering if `cyvcf2` has a sort of sample dict similar to `pysam` that I'm not aware. Or shall I have to create such dict?

Any advice would be much appreciated. Thanks in advance,

Alan

**Comment by brentp** [comment]
every time you do: `v.genotypes` or `v.gt_ref_depths`, etc. you are allocating a numpy array of 8000 entries. So for a single variant, 8000 times you are allocating an array of 8000 entries (*4).
Instead, do something like:
```Python

v = next(variant_file(f"{chrom}:{pos}-{pos}"))
gts = v.genotypes
rds = v.gt_ref_depths
ads = v.gt_alt_depths
dps = v.gt_depths
variant_dict["genotypes"] = [
    {
        "sample": [{"display": phenoid_mapping.get(s)}],
        "GT": gts[variant_file.samples.index(s)][:2],
        "AD": (rds[variant_file.samples.index(s)], ads[variant_file.samples.index(s)]),
        "DP": dps[variant_file.samples.index(s)],
    }
    for s in variant_file.samples
]
```
you can also get AD directly with `ADS = v.format("AD")`
then ADS[0] is [sample0_ref_depth, sample_0_alt_depth].

**Comment by brentp** [comment]
one other think is that `variant_file.samples` creates a new list each time, so you should do that once outside of your variant loop.

and you should create a look up sample.index once: lookup = `{s:i, for i, s in enumerate(variant_file.samples)}`
then use that as e.g. `"GT": gts[lookup[s]][:2] ` ... and so on.

**Comment by alanwilter** [comment]
Thanks @brentp!

**Comment by brentp** [comment]
post the same snippet again after you adjust and I'll make sure there's no more (hidden) n^2 stuff.

**Comment by alanwilter** [comment]
> one other think is that `variant_file.samples` creates a new list each time, so you should do that once outside of your variant loop.

That's not my case because my function only search for one variant at a time (it's a web app), but maybe I can cache this.

I will post here for sure my final snippet, for the moment, it's getting faster but I need to understand one thing: in the numpy.arrays, does the `-1` value mean `None`? If so, I need to cast this, for ex.:
```python
ads = [x if x > 0 else None for x in v.gt_alt_depths]
```
At first I need to get my final dict as much identical as possible to the `pysam` output.

**Comment by brentp** [comment]
yes, -1 means none. 
and I'd pass the samples to your function.

**Comment by alanwilter** [comment]
Dear @brentp, this is my current code which gives a result almost identical to `pysam`:
```python
v = next(variant_file(f"{chrom}:{pos}-{pos}"))
lookup = {s: i for i, s in enumerate(variant_file.samples)}
gts = [[item if item >= 0 else None for item in alist[:2]] for alist in v.genotypes]
rds = [x.item() if x >= 0 else None for x in v.gt_ref_depths]
ads = [x.item() if x >= 0 else None for x in v.gt_alt_depths]
dps = [x.item() if x >= 0 else None for x in v.gt_depths]
variant_dict["genotypes"] = [
    {
        "sample": [{"display": phenoid_mapping.get(s)}],
        "GT": gts[lookup[s]][:2],
        "AD": (rds[lookup[s]], ads[lookup[s]]),
        "DP": dps[lookup[s]],
    }
    for s in variant_file.samples
]
```
I've just started profiling, so far I can say the solution above with all its castings and restructuring is 37% faster than `pysam`.
I may still try with `ads = v2.format("AD")` but I don't think it will get faster.
I'm fine tuning my profiling to see the details (for one thing I want to know how much time is wasted with internet).

And last but not least. I said ***almost*** above because, for one example, over 8K samples (cols), I've got 3 different results for DP:
```
FORMAT
GT:AD:DP:GQ:PGT:PID:PL

Davina_UCL1000
./.:173,2:199:95:95,0,5354:.:.
DP: 199 (pysam); 175 (cyvcf2)

IoOFFS_Sample_SB9856
./.:182,24:209:99:106,0,5518:.:.e
DP: 209 (pysam); 206 (cyvcf2)

PrionUnit_sol1060
./.:0,0:2:0::.:.
DP: 2 (pysam); 0 (cyvcf2)
```
I see that `pysam` reads field DP while `cyvcf2` seems to read only field AD and hence calculated DP.

I'm not sure what this difference may mean, I may need to re-read VCF pdf doc again, but it would be great to hear from you about it.

Thanks in advance,
Alan

**Comment by brentp** [comment]
ref_depths and alt_depths are from AD[0] and AD[1] respectively. DP is from the actual DP field (whereas for cyvcf2, you are adding AD[0] + AD[1]).
Usually, AD is the count of reads that are used for genotyping (with low-qual reads/bases excluded) and DP is total depth.

I would try this to see if speed is better:
```
# instead of rds = [x.item() if x >= 0 else None for x in v.gt_ref_depths]
rds = v.gt_ref_depths.astype(object)
rds[rds < 0] = None
rds = rds.tolist()
```
and likewise to replace your other list comprehensions. I suspect that will get you a few more pct.

**Comment by alanwilter** [comment]
Thanks @brentp 
These changes actually made it 3% slower.
I'm closing this, many thanks again for your help.
