### ISSUE TITLE
Meaning of negative haplotypes

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [brentp/cyvcf2#178]
Hi there,

I've seen cyvcf2 return `-1` haplotype values - I've always assumed this means that the haplotype was not called (either due to lower ploidy or due to a missing call). However I just encountered a `-2` genotype, specifically
```
> var.genotypes.array()
[[-1 -2  1]
 [ 0  0  1]
 [ 0  0  1]]
```
Do all negative genotypes mean the same thing? If not, what does this mean?

**Comment by brentp** [comment]
you can see about that here: https://github.com/brentp/cyvcf2/pull/171/files

**Comment by LiterallyUniqueLogin** [comment]
Thanks!
