### ISSUE TITLE
Memory errors when trying to write records with missing contigs

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [brentp/cyvcf2#179]
If you open an unindexed VCF for reading that is missing a `##contig` line in the header, then cyvcf2 kindly emits the warning
```
[W::vcf_parse] Contig 'chr21' is not defined in the header. (Quick workaround: index the file with tabix.)
```
However, if you then try to write out any records from the VCF, Python starts throwing either Segmentation faults or throws memory errors like
```
*** Error in `python': double free or corruption (out): 0x0000556206c8ca50 ***
```
or
```
*** Error in `python': free(): invalid size: 0x0000556850d20810 ***
```
and produces memory dumps.

Can you fix this? It seems there are already lines of code [here](https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L299) and [here](https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L2356) that are supposed to catch this, but they aren't working.

I'd prefer that cyvcf2 just wrote out the VCF and didn't mind that the header was missing the correct contig line. If that outcome is not possible or desired, it would be nice if cyvcf2 threw a meaningful error instead of this mess.

#### Details:
I'm on cyvcf2 0.20.9, python 3.7.8
Using [this vcf](https://github.com/gymreklab/TRTools/blob/master/trtools/testsupport/sample_vcfs/test_advntr.vcf)
The following code reproduces the error:
```
>>> import cyvcf2
>>> vcf = cyvcf2.VCF("...")
>>> outvcf = cyvcf2.Writer("temp.vcf", vcf)
>>> rec = next(vcf)
[W::vcf_parse] Contig 'chr21' is not defined in the header. (Quick workaround: index the file with tabix.)
>>> outvcf.write_record(rec)
0
>>> exit()
*** Error in `python': free(): invalid size: 0x000055f6a9d55980 ***
======= Backtrace: =========
...
======= Memory map: ========
...
```
Adding `##contig=<ID=chr21>` to the VCF's header before running any of this code causes the code to run correctly.
I've found that executing the line `add_to_header("##contig=<ID=chr21>")` before the call to `cyvcf2.Writer(...)` also solves this problem, but that would involve intuiting in advance which contig lines are missing, and that doesn't work for my code which reads large VCFs and must stream the output instead of holding it forever in case the header must change.

**Comment by brentp** [comment]
This code:
```
mport cyvcf2
vcf = cyvcf2.VCF("test_advntr.vcf")
outvcf = cyvcf2.Writer("temp.vcf", vcf)
rec = next(vcf)
outvcf.write_record(rec)
outvcf.close()
vcf.close()
```
works fine for me.
Because of the way htslib does contigs, cyvcf2 uses this extra code:
https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L2356
to make things simpler.
Maybe this crashes things in the python shell? But I don't see that:
```
$ python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cyvcf2
>>> print(cyvcf2)
<module 'cyvcf2' from '/home/brentp/src/cyvcf2/cyvcf2/__init__.py'>
>>> vcf = cyvcf2.VCF("test_advntr.vcf")
>>> outvcf = cyvcf2.Writer("temp.vcf", vcf)
>>> rec = next(vcf)
[W::vcf_parse] Contig 'chr21' is not defined in the header. (Quick workaround: index the file with tabix.)
>>> outvcf.write_record(rec)
0
>>> outvcf.close()
>>> vcf.close()
>>> 
>>> cyvcf2.__version__
'0.20.9'
>>> exit()
$
```

**Comment by LiterallyUniqueLogin** [comment]
Ugh, looks like the issue was that my code wasn't calling `outvcf.close()`. Wish I'd thought of that sooner.

Not sure why that intersects with the contig issue, and its still not great that failing to do that gives such a weird error, but that's a very easy fix. Thanks for the help.
