### ISSUE TITLE
genotype column unnecessarily modified with trailing missing values (".")

### ISSUE THREAD

**Issue by eroller** [brentp/cyvcf2#18]
This:

chr1	125179503	.	A	AT	.	PASS	.	GT:GQ:GQX:DPI:AD:ADF:ADR:PL	.	1/1:24:60:9:0,9:0,7:0,2:204,27,0	.

gets modified to:

chr1	125179503	.	A	AT	.	PASS	.	GT:GQ:GQX:DPI:AD:ADF:ADR:PL	.:.:.:.:.:.:.:.	1/1:24:60:9:0,9:0,7:0,2:204,27,0	.:.:.:.:.:.:.:.

**Comment by brentp** [comment]
This is done by htslib. I suspect if you do "bcftools view $vcf" on the same vcf, it will do the same thing.

**Comment by eroller** [comment]
True. Moving this issue to htslib: https://github.com/samtools/htslib/issues/408
