### ISSUE TITLE
A way to quickly identify called / non called samples

### ISSUE THREAD

**Issue by lbeltrame** [brentp/cyvcf2#19]
I do a lot of sample-based filtering and excluding called/non called samples for a determined locus is an important step. Currently there's just the `num_called` property, but it doesn't tell *which* samples are called and which are not.

Possibly a numpy array of booleans called `called` might work?

**Comment by brentp** [comment]
for now, you can do:
```
called, = np.where(v.gt_types != UNKNOWN)
```
where UNKOWN = 2 by default or 3 if you opened with VCF(..., gts012=True)

**Comment by lbeltrame** [comment]
That would do indeed for the moment.

**Comment by brentp** [comment]
cool. I'll close for now.

**Comment by lbeltrame** [comment]
Given it's not documented there,  to which number do genotypes correspond to?  A quick glance in the source code didn't give immediate answers.

**Comment by brentp** [comment]
As of a recent commit, in unrelease cyvcf2, you'll be able to do
```
v = VCF(...)
v.HOM_REF, v.HET, v.HOM_ALT, v.UNKNOWN
```

to get the values. The default values are:
```
HOM_REF, HET, UNKNOWN, HOM_ALT = range(3)
```
if you open with `gts012=True` the UKNOWN and HOM_ALT are flipped.
