### ISSUE TITLE
Keep a changelog and follow semvar

### ISSUE THREAD

**Issue by mbhall88** [brentp/cyvcf2#190]
I wonder if you might consider [keeping a changelog](https://keepachangelog.com/en/1.0.0/)? For instance, some of my pipelines use v0.20.4; I would like to update them to the latest version, but it is very hard to actually figure out what has changed since that version.

Additionally, would you consider following [semvar](https://semver.org/) for versioning? i.e. the version jumped from v0.20.9 to v0.30.0, which seems a bit strange. It would be nice to know whether this was because you "added functionality in a backwards compatible manner" (i.e. a minor version bump) or not.

**Comment by davmlaw** [comment]
There's a "CHANGES.md" file now

**Comment by brentp** [comment]
I think this is resolved now by the CHANGES.md. 
Let me know if you see otherwise.

**Comment by mbhall88** [comment]
Thanks @brentp. The only last little point would be some pickiness around semver. As an example, I think v0.30.12 would normally constitute a minor version bump as new functionality was added in a backwards-compatible way?
Anyway, the changelog is very much appreciated. As is this library. Thanks for the great work!
