### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by danielecook** [brentp/cyvcf2#2]
Hi - I am getting the following error when installing:

        cyvcf2/cyvcf2.c:278:10: fatal error: 'numpy/arrayobject.h' file not found
        #include "numpy/arrayobject.h"
                 ^
        1 error generated.
        error: command 'clang' failed with exit status 1
        
        ----------------------------------------
    Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/s7/7x89ld8j1570grbn6_9sqlj40000gn/T/pip-build-AV3Ff2/cyvcf2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/s7/7x89ld8j1570grbn6_9sqlj40000gn/T/pip-PjCxnQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/s7/7x89ld8j1570grbn6_9sqlj40000gn/T/pip-build-AV3Ff2/cyvcf2

I have numpy installed and am using homebrew. 

__numpy__ version 1.9.2
__python__ version 2.7.10

**Comment by brentp** [comment]
hi @danielecook could you try the latest commit? I explicitly added the numpy
directory to the setup.py includes.

**Comment by danielecook** [comment]
@brentp thanks for replying so quickly. Still getting this error. 

	49 warnings generated.
	clang -bundle -undefined dynamic_lookup build/temp.macosx-10.10-x86_64-2.7/cyvcf2/cyvcf2.o cyvcf2/helpers.c cyvcf2/helpers.h -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lhts -o build/lib.macosx-10.10-x86_64-2.7/cyvcf2/cyvcf2.so
	clang: error: cannot specify -o when generating multiple output files
	error: command 'clang' failed with exit status 1

**Comment by brentp** [comment]
thanks for testing. I pushed one more commit that may resolve this. If not, I'll have to find a mac laptop to test on.

**Comment by danielecook** [comment]
That seems to have fixed it! Thanks. Dan

**Comment by brentp** [comment]
great! let me know if you have any other problems.
