### ISSUE TITLE
Retrieval of FORMAT string field fails

### ISSUE THREAD

**Issue by juliangehring** [brentp/cyvcf2#20]
Accessing the content of a FORMAT field with a text string content

```python
import cyvcf2
vf = vcf.VCF("test.vcf.gz")
v = next(vf)
v.format('ADP_ALL', int) ## control, works
v.format('RULE', str) ## fails
```

currently (latest release version 0.5.3 as well as built from master) fails with

> ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-046cd7d267ca> in <module>()
----> 1 v.format("RULE", str)
/usr/local/lib/python2.7/site-packages/cyvcf2/cyvcf2.pyx in cyvcf2.cyvcf2.Variant.format (cyvcf2/cyvcf2.c:21838)()
    894         shape[0] = <np.npy_intp> self.vcf.n_samples
    895         shape[1] = fmt.n # values per sample
--> 896         v = np.PyArray_SimpleNewFromData(2, shape, typenum, buf)
    897         ret = np.array(v)
    898         if vtype == str:
ValueError: data type must provide an itemsize

Example data (derived from `bug.vcf.gz` test case) with a 'RULE' format field that contains a text string:

    ##fileformat=VCFv4.2
    ##FILTER=<ID=PASS,Description="All filters passed">
    ##INFO=<ID=SOMATIC_CALL,Number=R,Type=Integer,Description="Boolean value for a somatic call for each allele.">
    ##FORMAT=<ID=ADP_ALL,Number=R,Type=Integer,Description="Number of all unique observations for each allele, inc. both low- and high-confidence.">
    ##FORMAT=<ID=RULE,Number=1,Type=String,Description="Text field">
    #CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Tumor
    7	55086956	.	C	G	0	.	.	ADP_ALL:RULE	6728,1:F
    7	55086957	.	T	A,C,G	0	.	.	ADP_ALL:RULE	6768,2,2,1:F2

**Comment by brentp** [comment]
Thanks for reporting and for the nice test-case. I have just pushed a fix for this.

I'm also about to add so that it's not necessary to specify the type so the call will just be e.g.:

```
v.format('RULE')
```
and it will look up the type in the header.

**Comment by brentp** [comment]
OK. that is added as of now so that it's no longer required to add the type in the call to format()

**Comment by juliangehring** [comment]
Great, thank you for fixing this so quickly and for the neat new feature. Do you think it is worth pushing a new release to pypi with both changes?

**Comment by brentp** [comment]
Good idea. I uploaded just now. And I'll push the latest to bioconda.

**Comment by juliangehring** [comment]
Nice, thanks!
