### ISSUE TITLE
Cyvcf2 Crashes in FIPS mode

### ISSUE THREAD

**Issue by KarlKeat** [brentp/cyvcf2#203]
We are trying to use cyvcf2 on a server where FIPS mode is enabled, but if we run our script (or even just go into the python interactive session and `import cyvcf2`) the entire program crashes with the error:

`crypto/fips/fips.c:154: OpenSSL internal error: FATAL FIPS SELFTEST FAILURE`

I think some type of hashing algorithm being called by cyvcf2 or htslib may be non-FIPS approved?

**Comment by ccwang002** [comment]
Could you share a bit more on how you install cyvcf2? Looks like the error came from htslib/libcurl/openssl, which is an optional feature to read remote VCF files.

You can try to build the cyvcf2 from source. While building htslib, don't link to libcurl and see if this error goes away:

```
git clone --recursive https://github.com/brentp/cyvcf2
cd cyvcf2/htslib
autoheader
autoconf
./configure  # <-- don't enable anything
make

cd ..
pip install -r requirements.txt
CYTHONIZE=1 pip install -e .
```

**Comment by KarlKeat** [comment]
I was using the pip version, but I just tried installing with conda and that seems to work, thanks.
