### ISSUE TITLE
Unexpected results for gt_types in haploid calls

### ISSUE THREAD

**Issue by wdecoster** [brentp/cyvcf2#204]
Hi Brent,

I am using cyvcf2 v0.30.8. I have split some samples by phase and called variants in there in a haploid fashion. In the VCF the GT is either 0 or 2 (alt allele1 actually does not occur).

A few columns from the VCF looks like
```
GT:GQ:DP:AF     0:23:23:0.6957  2:9:13:0.6154   0:21:13:0.6154  2:16:19:0.6316  0:24:17:0.8824  0:19:13:0.6154  0:22:10:0.8     0:24:14:0.9286      0:24:16:0.6875  0:27:24:0.7083  
```

And looking at variant.genotypes seems as expected:
```
[[0, False], [2, False], [0, False], [2, False], [0, False], [0, False], [0, False], [0, False], [0, False], [0, False]]
```

However, variant.gt_types looks odd. This is without setting gts012 to True. Hence, 2 would indicate a missing genotype, not a homalt?
```
[0 2 0 2 0 0 0 0 0 0]
```

I can provide a test file through email.

Cheers,
Wouter

**Comment by brentp** [comment]
I would say that gt_types has undefined behavior for non-diploid. I suppose I'd accept a PR to have it work in the haploid case, but it really is only useful for diploid.

**Comment by wdecoster** [comment]
Aha, okay that is good to know. I guess I'll use .genotypes then. Thanks!
