### ISSUE TITLE
Wheels are not being built

### ISSUE THREAD

**Issue by tomwhite** [brentp/cyvcf2#205]
The latest version on [PyPi](https://pypi.org/project/cyvcf2/) is 0.30.4, even though 0.30.8 has been released. The wheel build [failed](https://github.com/brentp/cyvcf2/actions/runs/752817153) but the logs have expired so unfortunately it's not possible to see what went wrong.

It might be worth building wheels on every main build (in addition to tags), and perhaps on a schedule too.

**Comment by tomwhite** [comment]
I'm not sure if this is the same problem, but even the 0.30.4 wheel (cyvcf2-0.30.4-cp38-cp38-manylinux2014_x86_64.whl) can't read remote VCF files on a GH Actions linux machine:

```
Python 3.8.11 (default, Jul  5 2021, 19:22:52) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cyvcf2 import VCF
>>> VCF('test.vcf.gz')
<cyvcf2.cyvcf2.VCF object at 0x7fbfcb7f84a0>
>>> VCF('https://github.com/brentp/cyvcf2/raw/master/cyvcf2/tests/test.vcf.gz')
[E::hts_open_format] Failed to open file "https://github.com/brentp/cyvcf2/raw/master/cyvcf2/tests/test.vcf.gz" : Input/output error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cyvcf2/cyvcf2.pyx", line 257, in cyvcf2.cyvcf2.VCF.__init__
  File "cyvcf2/cyvcf2.pyx", line 189, in cyvcf2.cyvcf2.HTSFile._open_htsfile
OSError: Error opening https://github.com/brentp/cyvcf2/raw/master/cyvcf2/tests/test.vcf.gz
```

If the file is local it works OK.

Environment:
```
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210718.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210718.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210718.1
```

I used https://github.com/mxschmitt/action-tmate to get a shell on the GH actions container.

**Comment by tomwhite** [comment]
It looks like #174 may be related.

**Comment by brentp** [comment]
I think we'd need `--enable-libcurl` in the configure ares in the build.yml

**Comment by brentp** [comment]
but that's already in the wheels.yml !?

**Comment by tomwhite** [comment]
Could possibly be a SSL library issue, along the lines of https://github.com/brentp/cyvcf2/pull/175#issuecomment-723499776?

Hopefully when I manage to SSH into a failing build I'll be able to get more info.

**Comment by brentp** [comment]
Let me know if you need anything from me to be able to get in. I added you as collaborator to the repo.

**Comment by tomwhite** [comment]
Thanks @brentp!

**Comment by brentp** [comment]
Thank you!

**Comment by tomwhite** [comment]
The mac wheel build contains the line (from trying to build htslib):

```
configure: error: cannot find required auxiliary files: config.guess config.sub
```

So configure isn't running properly, and the build fails. The problem seems to be autoconf 2.71 - downgrading to 2.69 (following the instructions in https://gist.github.com/oriolgual/2f881fa3a151dd5f643f755ddcf2a0bc from https://stackoverflow.com/questions/67442905/asdf-erlang-fails-to-compile-on-macos), made configure work again. There may be better ways of downgrading autoconf though.

The linux build has the same error, even though it seems to have autoconf 2.69 already, which is odd.

**Comment by brentp** [comment]
Maybe we need to update this: https://github.com/brentp/cyvcf2/blob/master/.github/workflows/wheels.yml#L44 ?

**Comment by brentp** [comment]
In ubuntu:18.04, libssl is here: `/usr/lib/x86_64-linux-gnu/`
and there is no directory or path to: `/usr/lib64/openssl1` unless that is being installed by something in github actions.

**Comment by brentp** [comment]
and headers are in: `/usr/include/openssl/`
not in `/usr/include/openssl11`

**Comment by tomwhite** [comment]
I'm not sure if these paths are correct or not, @horta might know.

The fix in #211 gets back to a point where the wheel build works again (I think).

**Comment by brentp** [comment]
seems it's working now, eh? https://github.com/brentp/cyvcf2/actions/runs/1048452332
if you agree, I'll tag a new release to verify.

**Comment by tomwhite** [comment]
Yes, please go ahead and tag.

**Comment by brentp** [comment]
0.30.9 now on pypi: https://pypi.org/project/cyvcf2/

thanks very much for fixing.
