### ISSUE TITLE
GT type for HOMALT with multiple alternative alleles

### ISSUE THREAD

**Issue by juliangehring** [brentp/cyvcf2#21]
For variants with multiple alt alleles, samples with a genotype homozygous in the second/third/... alt alleles are reported as `UNKNOWN`. Shouldn't they rather be `HOMALT`?

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Tumor	Normal
7	55086956	.	A	C,G	0	.	.	GT	0/1	2/2
7	55086957	.	A	C,G,T	0	.	.	GT	1/2	3/3
7	55086958	.	A	C,G,T	0	.	.	GT	1/1	2/3
```

```python
import cyvcf2 as vcf
vf = vcf.VCF("test.vcf")
v = next(vf)
v.gt_types
```

- `2/2` and `3/3` are reported as UNKNOWN (i.e. `2`) instead of HOMALT 
- `0/1`, `1/2` and `2/3` are correctly as HET (i.e. `1`)
- `1/1` is correctly reported as HOMALT (i.e. `3`)

**Comment by brentp** [comment]
This is known and expected behavior. If you want the original data, you can use v.format('GT')

There are arguments for changing the interpretation, but the HOM_REF, HET, HOM_ALT labels don't really work for multi-allelelics.

**Comment by juliangehring** [comment]
Thank you for the clarification.

> There are arguments for changing the interpretation, but the HOM_REF, HET, HOM_ALT labels don't really work for multi-allelelics.

Should then `1/1` in the last example be reported as HOMALT, since the ordering of the alt alleles is arbitrary? For example, `2/2` is as un(meaningful) as `1/1` in the context of this variant, isn't it? As an alternative, one may call all potential genotypes at a multi-allelic sites as unknown.

**Comment by brentp** [comment]
Please see the issue 30 and discussion there on how to get more direct access to the genotypes rather than going through gt_types which is a convenience method for bi-allelic sites in diploid samples.
