### ISSUE TITLE
gt_types has -1s and does not correspond to genotypes attribute

### ISSUE THREAD

**Issue by vsbuffalo** [brentp/cyvcf2#218]
This could be an issue with how I'm understanding the API documentation, or perhaps something more serious.

I have attached an MRE: (1) a small section of the high-coverage human 1000 genomes GVCFs, and (2) a simple MRE script called `mre.py` (at the very bottom).

Running it with:

```
$ python -i mre.py test.gvcf.gz
```

Looking at the dictionary of the `gt_types`:

```
>>> pos[10000458]
array([-1, -1, -1, -1, -1, -1,  0,  0, -1, -1, [...]]
```
First off, with `gts012=True` and `strict_gts=True`, why are these -1s coming up? 

Now the dictionary of `genotypes`:
```
>>> full_pos[10000458]
[[1, 1, False], [1, 1, False], [0, 1, False], [1, 1, False], [1, 1, False],
```
and finally for comparison, the GVCF at this position (looking at this in `zless`):

```
chr1    10000458        .       T       C,<NON_REF>     212.43  PASS    MQ=235.89;MQRankSum=2.268;ReadPosRankSum=1.713;FractionInformativeReads=1;R2_5P_bias=0;END=10000458;DP=8723     GT:AD:AF:DP:F1R2:F2R1:GQ:PL:SPL:ICNT:GP:PRI:SB:MB:MIN_DP:PS     1/1:2,25,0:0.926,0:27:2,18,0:0,7,0:38:125,41,0,824,84,868:255,35,0:0,0:87.597,37.597,0.00075516,450,115.82,450:0,34.77,37.77,34.77,69.54,37.77:1,1,12,13:1,1,13,12:.:.  
1/1:0,22,0:1,0:22:0,13,0:0,9,0:63:151,66,0,745,66,745:255,66,0:0,0:113.17,63.168,2.0709e-06,450,97.938,450:0,34.77,37.77,34.77,69.54,37.77:0,0,5,17:0,0,14,8:.:.        0/1:15,10,0:0.4,0:25:9,4,0:6,6,0:46:82,0,50,268,441,709:221,0,255:14,0:47.53,9.8368e-05,53,268.01,450,450:0,34.77,37.77,34.77,69.54,37.77:8,7,3,7:8,7,5,5:.:.   1/1:0,30,0:1,0:30:0,16,0:0,14,0:87:175,90,0,997,90,997:255,93,0:0,0:136.78,86.782,0,450,121.55,450:0,34.77,37.77,34.77,69.54,37.77:0,0,13,17:0,0,15,15:.:.      1/1:0,23,0:1,0:23:0,8,0:0,15,0:66:153,69,0,734,69,734:255,69,0:0,0:115.69,65.691,1.2943e-06,450,100.46,450:0,34.77,37.77,34.77,69.54,37.77:0,0,12,11:0,0,11,12:.:.
```

It's a bit hard to see, but the first two samples are homozygous ref, and the third sample is heterozygous. So the `genotypes` entry looks correct, but the data coming from `variant.gt_types` looks off. At other times, on different data (and different scripts than `mre.py`, I end up with non-sensical `gt_types` entries — very high numbers, etc. I wonder if this is perhaps a memory leak, or a numpy vector changing size or not being cleared properly? Just a thought. 

```py
import sys
from cyvcf2 import VCF
import numpy as np

vcf = VCF(sys.argv[1], gts012=True, strict_gt=True)

gts = []
full_gts = []
pos = dict()
full_pos = dict()
for variant in vcf:
  gts.append(variant.gt_types)
  pos[variant.POS] = variant.gt_types
  full_gts.append(variant.genotypes)
  full_pos[variant.POS] = variant.genotypes

g = np.array(gts)
```

[test.gvcf.gz](https://github.com/brentp/cyvcf2/files/6904247/test.gvcf.gz)

**Comment by vsbuffalo** [comment]
sorry — hold off, Github submitted this before I intended. I will edit the original to complete it.

**Comment by brentp** [comment]
Hi Vince, gt_types will only work for bi-allelic sites. I think the best change would be to throw an error or warning for multi-allelic sites.

**Comment by vsbuffalo** [comment]
Hi Brent,

Thanks — I was trying to process an intermediate GVCF file before GATK's genotypeGVCF was run on it (and hence it has those `<NON_REF>` tags that haven't been resolved). I think this is too much an edge case and not worth support generally, so I'll close this issue. Thanks for the help!
