### ISSUE TITLE
Why are AD and DP > 0 but gt_depths all -1?

### ISSUE THREAD

**Issue by vsbuffalo** [brentp/cyvcf2#219]
Here's another issue I've run into, perhaps because I'm misunderstanding something about VCFs.

I have a per-basepair VCF (example attached as `small.gvcf.gz`). In ipython:

```python
from cyvcf2 import VCF
vcf = VCF("small.gvcf.gz")
var = next(vcf)
np.all(var.gt_ref_depths == -1) # True
np.all(var.gt_depths == -1) # True
np.all(var.gt_alt_depths == -1) # True

np.sum(var.format('AD') > -1) # 460
np.sum(var.format('DP') > -1) # 460
var.num_called # 460
```

This is looking at the first line of the VCF (`var.POS = 224000000`). The sum of `var.format('DP')` matches the `DP` in the `INFO` line, and my expectation would be that the genotype depths are not all missing (-1). 
[small.gvcf.gz](https://github.com/brentp/cyvcf2/files/6979298/small.gvcf.gz)

**Comment by brentp** [comment]
cyvcf2 uses AD for `gt_*_depths` and expects diploid. your vcf looks like:
```
GT:AD:DP:ICNT:RGQ:SPL   0/0:25:23:26,0:60:0,61,255
```
where there's only a single value for AD. 
the `gt_*_depths` and `gt_types` will only work for diploid samples, variants. I think we could throw an exception here when `len(AD) != 2 * vcf.n_samples`

**Comment by vsbuffalo** [comment]
Yea, that makes sense. I think an exception would be a good way to handle it, though for reference, this is a GVCF right out of GATK's GenotypeGVCFs. I think they're probably saving space by omitting the extra `25,0` since that'd be a lot of extra info for non-polymorphic sites.
