### ISSUE TITLE
numpy dependency in setup.py mishandled

### ISSUE THREAD

**Issue by Drin** [brentp/cyvcf2#22]
I'm not entirely sure what the best solution is in this case, but in setup.py, numpy is specified as a dependency, but it is imported at the top of the file before the dependency can be satisfied.

I suspect that this problem can be addressed via the example here: http://docs.scipy.org/doc/numpy-dev/f2py/distutils.html and the documentation here: http://docs.scipy.org/doc/numpy/reference/distutils.html

**Comment by brentp** [comment]
This is a good point and should be fixed.
I would welcome a PR to fix this, but it's not at the top of my list since installing from conda is easy and simple.

Looks like the scipy setup.py might be a good one to follow:
https://github.com/scipy/scipy/blob/master/setup.py

**Comment by Drin** [comment]
note that Cython is also causing the same issue in an environment where Cython is not added.

**Comment by Drin** [comment]
not sure how to reply, @brentp , but yeah I just wanted to track the issue. I'm actually in the process of preparing a PR, but this could become a deep hole. I'll try to do tonight or so :)

**Comment by brentp** [comment]
ok. a PR would be great! didn't mean to discourage you at all, just wanted to be realistic about me tackling this.

**Comment by Drin** [comment]
haha, np. I assumed it would be a low priority. A simple work around is not too difficult anyways.

**Comment by brentp** [comment]
this is closed by @juliangehring in #25.

**Comment by Drin** [comment]
Thanks @juliangehring !
