### ISSUE TITLE
libdeflate

### ISSUE THREAD

**Issue by brentp** [brentp/cyvcf2#224]
cyvcf2 is substantially faster on BCF when libdeflate is used. 
see: https://github.com/brentp/vcf-bench

this takes the time from ~8 seconds to ~4 seconds.

would be nice to get this into the default build

**Comment by grahamgower** [comment]
I'm keen to help out with this, but I'm not sure what kind of integration you'd consider acceptable. I also see #145 is still pending which might need addressing first?

**Comment by brentp** [comment]
I think 145 is no longer valid after the work from @ccwang002 mentioned there. 
It looks like bioconda build is using libdeflate.
