### ISSUE TITLE
support python 3.10 (tests)

### ISSUE THREAD

**Issue by brentp** [brentp/cyvcf2#226]
Here is the test output for python 3.10 seems to be a failure with nose tests:
https://github.com/brentp/cyvcf2/runs/4279722226?check_suite_focus=true

**Comment by grahamgower** [comment]
Nose is well and truly unmaintained. I can probably move things over to pytest if you think that's ok? Its almost a drop in replacement, and probably just needs some CI adjustments.

**Comment by brentp** [comment]
yes please.
