### ISSUE TITLE
Use Python's logging module instead of writing directly to stderr

### ISSUE THREAD

**Issue by grahamgower** [brentp/cyvcf2#228]
There are a few occasions where cyvcf2.pyx writes to stderr. It would be nice to be able to capture and/or filter these in some cases. Would it be ok if these were replaced with calls to the [`logging`](https://docs.python.org/3/library/logging.html) module? There seem to be some caveats with using the logger inside cython, but I think it should be ok if logger attributes related to stack frames aren't used.

The specific message I want to silence right now is "no intervals found for ...", because I'm deliberately doing `next(vcf(contig_id))` for each contig id found in the header to see if any variants exist for that contig (I then create a mapping from contig id to vcf file, which is handy for vcfs split by chromosome).
https://github.com/brentp/cyvcf2/blob/2addcaf097bba1b6fa219a260e6ec39a2b2e936c/cyvcf2/cyvcf2.pyx#L403
https://github.com/brentp/cyvcf2/blob/2addcaf097bba1b6fa219a260e6ec39a2b2e936c/cyvcf2/cyvcf2.pyx#L457

**Comment by brentp** [comment]
> Would it be ok if these were replaced with calls to the logging module

Yes, that would be great!
