### ISSUE TITLE
Memory leak of string conversion

### ISSUE THREAD

**Issue by juliangehring** [brentp/cyvcf2#23]
Following the example from the readme, it seems to me converting variants back to their string representation causes a memory leak.

As an example using public data from ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/, repeated conversions to strings

```python
import cyvcf2 as vcf
vf = vcf.VCF("ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz")

for v in vf:
    s = str(v)
```
increase the memory of the python process to several GB. Warning, this can quickly eat up the entire memory of the machine before all variants in the example have been processed! Without calling `str` or `print`, the process would require about 12MB. I have seen the same effect with other VCF files, so I don't think it is related to the data itself.

Can the `str` function be used differently, without consuming this much memory?

Versions:
python 2.7.12, cyvcf2 0.5.5

**Comment by brentp** [comment]
Thanks for the bug report. I just pushed a fix for this. And uploaded to pypi.
