### ISSUE TITLE
Can I get a variant by ID?

### ISSUE THREAD

**Issue by CholoTook** [brentp/cyvcf2#234]
I don't see how in the docs.

**Comment by brentp** [comment]
You would need to iterate over each variant in the file and check if `variant.ID == "$ID"`
there is no mechanism in VCF itself it index by ID.

**Comment by CholoTook** [comment]
I see, thanks for the quick response :-)

Currently I have code like this:
```
vcf = VCF(vcf_file)
for v in vcf:
    snps_by_ids[v.ID] = v
```
I wondered if there could be an array in there for the ID?

**Comment by brentp** [comment]
ID will always be a string or None.
