### ISSUE TITLE
Can't capture the stdout of Writer("-", vcf) using Python contextlib

### ISSUE THREAD

**Issue by Lukez-pi** [brentp/cyvcf2#257]
Hi, @WSDeWitt and I are interested in capturing the stdout of Writer("-", vcf) in Python to perform some downstream unit tests, but for some reason the vcf output cannot be captured through `contextlib.redirect_stdout`. To illustrate the problem, I have a minimal vcf file named `test.vcf` shown below
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=248387328>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1 sample2
chr1    2       .       A       T       30      PASS    AN=3;AC=2       GT      1|.     1/0
```
and my Python script is as follows:
```python
from cyvcf2 import VCF, Writer
from io import StringIO
from contextlib import redirect_stdout

def create_new_vcf():
    print("printing random content")
    vcf = VCF("test.vcf")
    vcf_write = Writer("-", vcf)
    for variant in vcf:
        vcf_write.write_record(variant)

string_io = StringIO()
with redirect_stdout(string_io):    
    create_new_vcf()
print(f"\n\nthe captured stdout: \n{string_io.getvalue()}")
```
If I were to run this Python script from the command line, the output looks like this:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=chr1,length=248387328>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1 sample2
chr1    2       .       A       T       30      PASS    AN=3;AC=2       GT      1|.  1/0


the captured stdout: 
printing random content

```
What's interesting to me is that the VCF output was still printed out as part of the output, but it was not captured by `redirect_stdout`, only the printed statement "printing random content" was captured. Therefore I was wondering if you know what the issue is and how might I go about resolving this, thanks!

**Comment by brentp** [comment]
I think you might be able to use:
```
vcf_write = Writer(sys.stdout.fileno(), vcf)
```
or, I think you can simply use `sys.stdout` without the `.fileno()`.

**Comment by Lukez-pi** [comment]
Hi Brent,

Thanks for the reply! I tried replacing `"-"` with both `sys.stdout` and `sys.stdout.fileno()`, but got similar errors:
```
File "cyvcf2_issue.py", line 15, in <module>
    create_new_vcf()
  File "cyvcf2_issue.py", line 9, in create_new_vcf
    vcf_write = Writer(sys.stdout, vcf)
  File "cyvcf2/cyvcf2.pyx", line 2322, in cyvcf2.cyvcf2.Writer.__init__
  File "cyvcf2/cyvcf2.pyx", line 179, in cyvcf2.cyvcf2.HTSFile._open_htsfile
io.UnsupportedOperation: fileno
```
I'm not sure if this is related to my attempt of trying to redirect `stdout` to an `io.StringIO` object, when I commented out all the code outside of the function:
```python
string_io = StringIO()
with redirect_stdout(string_io):    
    create_new_vcf()
print(f"\n\nthe captured stdout: \n{string_io.getvalue()}")
```
and replaced it with a simple function call `create_new_vcf()`, the error disappeared, but the vcf output no longer shows up in the command window.

**Comment by brentp** [comment]
oh, the contextlib function is messing with sys.stdout so it doesn't have a fileno...
I think you'll have to write to a file and the stream and print that,
or you can just use the str methods on the vcf to write it directly. something like:
```
print(vcf.raw_header, end="")
for v in vcf:
    print(str(v))
```

**Comment by Lukez-pi** [comment]
I see, the `print` method works quite well! I did some quick test and found that `print(str(v))` and `write_record(v)` are quite similar in terms of runtime performance, just want to check and see whether this squares with your expectation? Thanks!

**Comment by brentp** [comment]
that sounds reasonable. write_record would be faster if you are writing bcf, but otherwise, they'd be quite similar.

**Comment by Lukez-pi** [comment]
Thanks again for your help!
