### ISSUE TITLE
Dropping genotype data when writing a new VCF file

### ISSUE THREAD

**Issue by vahidelyasi** [brentp/cyvcf2#258]
Hi, I am parsing a large VCF file with around 100K samples and after adding some INFO fields I try to write a new VCF file which only has 8 columns, essentially dropping genotype information and format column. Is there a way to only write the first 8 column of a record using vcf writer? Thanks

**Comment by brentp** [comment]
Hi, did you try `vcf.set_samples([])` or similar before opening the writer?

**Comment by vahidelyasi** [comment]
Thanks for your prompt response. 
I didn’t set the samples to null as I initially need to use genotype data to get the heterozygous carries and add this information into INFO column. For each record, once I add this information to INFO variable, I then attempt to add the record to a new VCF without the genotype information for the record. 
I tested this approach using pyVCF and by using record.samples.clear() just before writing the record, I get the desired output.

**Comment by brentp** [comment]
I see. I think you'd have to open 2 different files for reading and use set_samples([]) in one of them, open the writer with that one and perform the calcuations with the other reader.
This might be possible with htslib machinery, but it's not possible more directly in cyvcf2.

**Comment by vahidelyasi** [comment]
Okay many thanks for letting me know, I'll try that.

**Comment by waltergallegog** [comment]
Hi @vahidelyasi did you try the solution? did it work for you?

I have tried using `set_samples([])` but when I iterate over the records I still get all the samples present in the vcf.
I can choose only one of the samples (for example `set_samples(['SAMPLE1']), but leaving the list empty gives me all of them.

**Comment by vahidelyasi** [comment]
Hi @waltergallegog, I had the exact same issue and ended up adding 1 sample to set_samples(["SAMPLE1"]). After processing, I removed the column for that sample in bash.

**Comment by brentp** [comment]
With the latest release, you should be able to use set_samples([]) to none of the samples. please let me know if that's not the case.
