### ISSUE TITLE
Issues with using String in format field

### ISSUE THREAD

**Issue by ThomVett** [brentp/cyvcf2#259]
Hello!

Was just starting to try out `cyvcf2` and was having some issues setting string values in format fields - would appreciate help here. Thanks :)

Environment:
- Python: 3.8.12
- cyvcf2: 0.30.18

I use the following code snippet (I don't think the vcf file is the problem but how i am adding the string):
```
vcf = VCF('vcf_examples/2227546-full_variant_table_with_samples.vcf')

# vcf.samples contains the single sample that my file has
# Adding the GT format field - Number = 1

vcf.add_format_to_header({
    'ID': 'GT',
    'Description': 'Genotype',
    'Type': 'String',
    'Number': '1'
})

for v in vcf:
    v.set_format("GT", np.array([["./1"]], dtype="a3"))
```

throws the following error:
`Exception: Setting string type format fields with number>1 are currently not supported`

which is not super clear to me as the shape of the array i am trying to set is `(1, 1)`.

On a related note - is it possible to add a sample programmatically after having loaded  a vcf file that does not have any?

Thanks in advance for your help.

**Comment by brentp** [comment]
Hi, if you want to set genotypes, you should use code like in the tests:
```
def test_set_gts():
    vcf = VCF('{}/test-format-string.vcf'.format(HERE))
    v = next(vcf)

    v.genotypes = [[1, 1, True], [0, 0, False]]
    assert get_gt_str(v) == ["1|1", "0/0"]

    v.genotypes = [[-1, 1, False], [-1, 0, False]]
    assert get_gt_str(v) == ["./1", "./0"]

    v.genotypes = [[-1, -1, False], [0, 0, True]]
    assert get_gt_str(v) == ["./.", "0|0"]

    v.genotypes = [[2, 2, True], [0, 2, True]]
    assert get_gt_str(v) == ["2|2", "0|2"]

```
The final value in each triplet indicates phasing.

Regarding adding samples, that's not possible with cyvcf2 right now.

**Comment by ThomVett** [comment]
Thanks a lot @brentp - will try that out :)

**Comment by dbolser** [comment]
Given there is a test for this, I guess the issue can be closed? @ThomVett can you make a PR with an EXAMPLES section of the README?

**Comment by ThomVett** [comment]
yes we can close - will put the PR on my to do :)

**Comment by dbolser** [comment]
Thanks @ThomVett, looking forward to your PR!

Dan.
