### ISSUE TITLE
Allow listing the FORMAT types from the header

### ISSUE THREAD

**Issue by lbeltrame** [brentp/cyvcf2#26]
Useful when you assemble VCFs from different callers and you have to check for caller-specific FORMAT types.

Currently `Variant.format()` needs the key to be known in advance.

**Comment by brentp** [comment]
this was implemented recently so in the current version, it gets the type from the header.

**Comment by lbeltrame** [comment]
Perhaps I worded it incorrectly: for each record I have to issue `variant.format(key)` but not all records may have the same `FORMAT` (they're merges from different callers) so I don't know `key` in advance. I'd need a way to list them.

**Comment by brentp** [comment]
oh, I see. I didn't realize this wasn't available. I'll add it to variant.FORMAT today.

**Comment by brentp** [comment]
I added this under variant.FORMAT, which returns a list and pushed a new version to pypi.
