### ISSUE TITLE
Conda packages are out of date

### ISSUE THREAD

**Issue by tomwhite** [brentp/cyvcf2#269]
I'm not sure if this is the right place to raise this, but I noticed that the conda packages at https://anaconda.org/bioconda/cyvcf2 are for cyvcf2 0.30.16, and [the build for 0.30.19 appears to be broken](https://github.com/bioconda/bioconda-recipes/pull/37181).

**Comment by tomwhite** [comment]
The conda build failed again for 0.30.22. The error is

```
To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

**Comment by brentp** [comment]
where do you see that? I am looking [here](https://github.com/bioconda/bioconda-recipes/actions/runs/5047172594/jobs/9056907784?pr=37181)
via the [PR](https://github.com/bioconda/bioconda-recipes/pull/37181)
I don't see how to fix the conda build.

**Comment by tomwhite** [comment]
That's odd, it was from an Azure run that doesn't seem to be linked from https://github.com/bioconda/bioconda-recipes/pull/37181 anymore.

**Comment by mencian** [comment]
Greetings. I have created a PR to update cyvcf2 to v0.30.22 [here](https://github.com/bioconda/bioconda-recipes/pull/41403). Can you review the PR when you get a chance?

**Comment by brentp** [comment]
I have accepted the PR there. Thanks for doing this.
