### ISSUE TITLE
Linux packages for 0.30.20 are missing from pypi

### ISSUE THREAD

**Issue by tomwhite** [brentp/cyvcf2#270]
See https://pypi.org/project/cyvcf2/#files

Looks like it may be due to

https://github.com/brentp/cyvcf2/blob/46297923815e5a2e51a6307c802c82f8532635c7/.github/workflows/wheels.yml#L41

not matching

https://github.com/brentp/cyvcf2/blob/46297923815e5a2e51a6307c802c82f8532635c7/.github/workflows/wheels.yml#L25

@brentp?

**Comment by aryarm** [comment]
Hi there,

I noticed that a fix for this issue was merged and tagged but never uploaded to PyPI. Any chance someone could upload it?

Thanks in advance! And thanks for creating cyvcf2! It's such a useful library.

**Comment by tomwhite** [comment]
@brentp it looks like the [deploy to pypi failed](https://github.com/brentp/cyvcf2/actions/runs/5007758631/jobs/8975189097), as the version in https://github.com/brentp/cyvcf2/blob/main/cyvcf2/__init__.py (0.30.20) is different to the tag (0.30.21).

**Comment by brentp** [comment]
arghhh! Thanks @tomwhite I pushed 0.30.22 with hopefully everything matching.

**Comment by tomwhite** [comment]
Just to confirm the new 0.30.22 packages are working now. Thanks @brentp!

**Comment by brentp** [comment]
Thank you @tomwhite very much for keeping cyvcf2 operational!
