### ISSUE TITLE
Issues with cyvcf2 memory allocation

### ISSUE THREAD

**Issue by adrienlemeur** [brentp/cyvcf2#273]
Hello, I have a bug when trying to import multiple VCF one after another :

RPython traceback:
  File "pypy_module__warnings.c", line 1446, in do_warn_explicit
  File "pypy_objspace_std.c", line 12620, in makespecialisedtuple
*** Invalid usage of a dying CPython object ***

cpyext, the emulation layer, detected that while it is calling
an object's tp_dealloc, the C code calls back a function that
tries to recreate the PyPy version of the object.  Usually it
means that tp_dealloc calls some general PyXxx() API.  It is
a dangerous and potentially buggy thing to do: even in CPython
the PyXxx() function could, in theory, cause a reference to the
object to be taken and stored somewhere, for an amount of time
exceeding tp_dealloc itself.  Afterwards, the object will be
freed, making that reference point to garbage.
>>> PyPy could contain some workaround to still work if
you are lucky, but it is not done so far; better fix the bug in
the CPython extension.
>>> This object is of type 'cyvcf2.cyvcf2.VCF'
Aborted (core dumped)

When I analyze one file at a time it seems to work
- Adrien

**Comment by brentp** [comment]
Hi, it's very hard to debug this as you're using pypy and apparently some other layers of indirection.
Could you point to the repo or code that shows this issue? I don't know much about cpython extensions and pypy, but that would be a start.

**Comment by adrienlemeur** [comment]
Hmm, I thought pypy was used at some point by cyvcf2 because I don't really now what it is. I just use very standard libraries (argparse, re, sys) in addition to cyvcf2. 
It appears the problem solved itself by deactivating mamba... ? I really do not understand what is going on here tbh

**Comment by adrienlemeur** [comment]
Either way, it solved itself and I don't think it came from cyvcf2, thank you anyway !
