### ISSUE TITLE
variant.format('GT') yields unexpected string format

### ISSUE THREAD

**Issue by gnxsf** [brentp/cyvcf2#275]
Attempting to extract genotypes using variant.format('GT') yields an unexpected format.

When I extract with bcftools:
```
bcftools query -f "%REF %ALT [%GT ]\n" one_pos_prac.vcf
./. 0/1 ./. ./. ./. ./. 0/1 ./. 1/1 ./. 0/0
```

When I extract using variant.format('GT') from cyvcf2:
```
from cyvcf2 import VCF
for variant in VCF("one_pos_prac.vcf"):
    print(variant.format('GT'))
```
```
['' '\x02\x04' '' '' '' '' '\x02\x04' '' '\x04\x04' '' '\x02\x02']
```

Is this the expected output format?

**Comment by brentp** [comment]
Hi, GT is a special case in VCF format, you can access in cyvcf2 as variant.genotype() to get some objects or variant.genotypes to get  a list for each sample Indicating the allele and phasing.

        e.g. [0, 1, True] corresponds to 0|1
        while [1, 2, False] corresponds to 1/2

**Comment by gnxsf** [comment]
Thanks for your quick response! Out of curiosity, what is the utility of the current GT format? i.e. is returning GT in the '\x02\x04' format useful for some other reason that I'm not aware of?

**Comment by brentp** [comment]
There is no utility, it must be special-cased. It is stored as integers, but you must use bit operations to get at the actual genotype info. It is shown in the VCF as a String.
