### ISSUE TITLE
Floating point imprecision

### ISSUE THREAD

**Issue by 3ng7n33r** [brentp/cyvcf2#277]
# Steps to Reproduce the Problem
Use any vcf with a floating point number. In my example case, I have a one line vcf with MQM=59.5147.
In python:
```
from cyvcf2 import VCF
for variant in VCF("path/to/file.vcf"):
     variant.INFO.get('MQM')
 
>>> 59.51470184326172
```

# Expected Behavior
```
>>> 59.5147
```
# Actual Behavior
```
>>> 59.51470184326172
```
Is this a known issue? Are there options to mitigate this in the current version?

**Comment by brentp** [comment]
Can you share a VCF, including header and single variant that shows this problem? I suspect this is not within cyvcf2 as it doesn't do anything with number formatting. You could also try bcftools view on your vcf and see if you have the same result.

**Comment by 3ng7n33r** [comment]
[example_faulty_float.vcf.gz](https://github.com/brentp/cyvcf2/files/12406642/example_faulty_float.vcf.gz)

I attached one vcf where it happens but it happens at almost every vcf we process.

For this example:
```
>>> from cyvcf2 import VCF
>>> for variant in VCF("/home/diagho/Documents/vcf/example_faulty_float.vcf"):
...     variant.INFO.get("MQ")
... 
[W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
24.950000762939453
27.84000015258789
27.84000015258789
27.969999313354492
23.34000015258789
28.860000610351562
28.940000534057617
```

Values expected:
```
24.95
27.84
27.84
27.97
23.34
28,86
28.94
```

MQ is also just an example. It happens with pretty much any other column containing a float.

**Comment by brentp** [comment]
Hi, this is python behavior due to the representation of floats:

```
In [9]: print(float(np.float32(24.95)))
24.950000762939453
```
that takes one of your numbers, converts it to a numpy float32 and back to a python float and you get the result that you see. So this is not a cyvcf2 issue.

**Comment by brentp** [comment]
note that you can get the representation you like with something like this:
```
In [12]: "%.7g" % float(np.float32(24.95))
Out[12]: '24.95'
```

**Comment by 3ng7n33r** [comment]
Thank you Brent. I agree that this is a problem with the representation of floats in python but I think this is nonetheless an unexpected output.
Do you think the float formatting step could be included in cyvcf?

**Comment by brentp** [comment]
No, this is outside the scope. You're printing floating point numbers.

**Comment by 3ng7n33r** [comment]
@brentp agree to disagree. I'm not printing anything, I'm receiving an unexpected return value.


In practice, we save these values directly to the database and that is where the issue initially showed up.


I would not expect a parser to alter values while parsing but I guess there's nothing I can do about it. We will implement a formatter to check for float values and correct them before adding them to the database.


Anyway, thank you for your work on this project, open source is unthankful.
