### ISSUE TITLE
Processing BED?

### ISSUE THREAD

**Issue by dbolser** [brentp/cyvcf2#282]
I know this is focused on VCF, but I'm thinking of creating a cython wrapper around htslib for BED files (since htslib can index any columnar format like tabix (I think...)).

However, I'd happily keep using cyvcf2 (at least the htslib part) if I could...

One question though... My motivation isn't for positional indexing, rather for multithreaded reading of the gz (which I assume can be supported by using the index to give each thread a different chunk to process...) Is this how cyvcf2 gets it's speed boost? (sorry for being lazy and not reading the paper!)

**Comment by brentp** [comment]
Hi, you can use tabix in pysam for this: https://pysam.readthedocs.io/en/latest/usage.html#working-with-tabix-indexed-files
there's also pytabix.

cyvcf2 gets speed from doing as much as possible in C and writing efficient methods in cython.

**Comment by dbolser** [comment]
Thank you!
