### ISSUE TITLE
Importing 64bit integers in FORMAT?

### ISSUE THREAD

**Issue by barneyhill** [brentp/cyvcf2#285]
Dear Brent Pedersen, 

I'm currently trying to read [bcftools bcsq bitmask output](https://samtools.github.io/bcftools/howtos/csq-calling.html) with cyvcf2. I can control the maximum length of the bitmask and want to increase it from 32 bit to 64 bit with the bcftools csq flag --ncsq 15 -> --ncsq 63. 

In order to import this 64bit mask do you think it would be as simple as locally changing [this line](https://github.com/brentp/cyvcf2/blob/c1a2dba963050b9fed3056ee3e6f80e974a2f0b7/cyvcf2/cyvcf2.pyx#L1330C73-L1330C73) to int64 when getting the record's format: `record.format('BCSQ', vtype='Integer')`?

Many Thanks, we've found cyvcf2 to be invaluable,
Barney

**Comment by brentp** [comment]
Hi Barney, do you mean references like: `BCSQ=@122106101` that should still be read as a string and then converted in python to an integer or otherwise used to look up the reference.
I don't think changing --ncsq from 15 to 63 will change from 32 to 64 bit, it will just allow bcftools to report up to 63 consequences for sites that overlap 63 or more transcripts.

**Comment by barneyhill** [comment]
I believe `ncsq` controls the number of bits used in the FORMAT/bcsq bitmask, see: https://github.com/samtools/bcftools/issues/2051. I should clarify that i'm reading this bitmask as a int but then converting it to a binary bitmask like so:

```
def get_haplotypes_at_index(bitmask_array: np.ndarray, index: int) -> Tuple[np.ndarray, np.ndarray]:
    """
    Returns haplotype presence information for a given index across a NumPy array of bitmasks.

    Parameters:
    bitmask_array (np.ndarray): Array of bitmasks.
    index (int): The index position to check in each bitmask.

    Returns:
    Tuple[np.ndarray, np.ndarray]: Two boolean arrays indicating the presence of haplotype 1 and 2 at the given index.
    """

    # Masks for checking the specific bit position for each haplotype
    haplo1_mask = 1 << (2 * index)
    haplo2_mask = 2 << (2 * index)

    # Check if the haplotype bits are set across the array
    haplo1_set = (bitmask_array & haplo1_mask) != 0
    haplo2_set = (bitmask_array & haplo2_mask) != 0

    return haplo1_set, haplo2_set

```

**Comment by brentp** [comment]
I don't use sample stuff from bcftools csq, so don't follow this, but for the 64 bit question, you'd have to implement the 
`bcf_get_info_values` for `BCF_HT_LONG` in cyvcf2. That's not supported as it didn't exist when I started this project.
The other types in the cyvcf2 function you linked use the macros provided by htslib:
```
    #define bcf_get_info_int32(hdr,line,tag,dst,ndst)  bcf_get_info_values(hdr,line,tag,(void**)(dst),ndst,BCF_HT_INT)
    #define bcf_get_info_float(hdr,line,tag,dst,ndst)  bcf_get_info_values(hdr,line,tag,(void**)(dst),ndst,BCF_HT_REAL)
    #define bcf_get_info_string(hdr,line,tag,dst,ndst) bcf_get_info_values(hdr,line,tag,(void**)(dst),ndst,BCF_HT_STR)
    #define bcf_get_info_flag(hdr,line,tag,dst,ndst)   bcf_get_info_values(hdr,line,tag,(void**)(dst),ndst,BCF_HT_FLAG)
```
I'd gladly accept a PR that added support for BCF_HT_LONG via `bcf_get_info_int64` depending on when that was added to htslib.
