### ISSUE TITLE
Add Variant FORMAT entries

### ISSUE THREAD

**Issue by RPSeq** [brentp/cyvcf2#29]
I have had no issues adding new INFO and FORMAT fields to a VCF header, and also can add new INFO fields to individual Variant objects. However, there does not seem to be any way to add new FORMAT items to a Variant object. Do you know of any workarounds for this- perhaps by creating a new Variant object with updated FORMAT fields?

NOTE: This is not especially important, just a feature that would be somewhat useful to me.

**Comment by brentp** [comment]
yeah, this would be useful, I haven't done it yet because it's hard. :( 
I'll have another look soon.

**Comment by shubhamsaini** [comment]
Can I get an example on how to add a new FORMAT field?

For example, I'm trying to add a field called ZZ, which is similar to GT. So my VCF would look like:
`GT:ZZ 0|1:p|q`
