### ISSUE TITLE
cyvcf2 pip install fails on travis-ci

### ISSUE THREAD

**Issue by danielecook** [brentp/cyvcf2#3]
Hi - I'm not sure if this is an error on my part (it may very well be). I'm incorporating cyvcf2 into a package I am developing and am able to install it fine locally. However, I recently started playing around with Travis CI and am unable to install cyvcf2 using the service. This is the error I am getting:

```
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-fY1AZz/cyvcf2/setup.py", line 4, in <module>
    
        from Cython.Distutils import build_ext
    
    ImportError: No module named Cython.Distutils
```

Any idea why this is happening? I haven't been able to turn up much explanation googling around. And I'm not familiar with cython.

This log illustrates the issue in greater detail: https://travis-ci.org/AndersenLab/vcf-toolbox/builds/84329365

**Comment by brentp** [comment]
Hi, just noticed this now. I've had the same problem. I got around it by installing cython first with an install section like this:

```

install:
    - pip install cython
    - pip install -r requirements.txt
    - python setup.py install
```

**Comment by danielecook** [comment]
Thanks that took care of it!
