### ISSUE TITLE
Handling multiple alternative alleles

### ISSUE THREAD

**Issue by wdecoster** [brentp/cyvcf2#30]
When iterating over a (large) multisample vcf file, how are multiple alternative alleles encoded in variant.gt_types? What would be the best way to classify those correctly?

**Comment by brentp** [comment]
Hi, this is also covered in this issue: https://github.com/brentp/cyvcf2/issues/21#issuecomment-249604589

for the most part, gt_types is a convenience provided for cases when the VCF has be decomposed or when there is only a single alternate allele. I'm open to suggestions on improving this.

**Comment by wdecoster** [comment]
Perhaps instead of using HOM_ALT use HOM_NONREF? But this doesn't solve the complexity of a sample having two alternative alleles and no reference allele. Although it's technically a heterozygote, but not correct to classify that sample as REF/ALT heterozygote.

For my purpose (create a tab separated file listing the carriers per variant) it would also be an approximate solution to split multiple alternative alleles over multiple lines.

**Comment by brentp** [comment]
Yes, these are the decisions for which I haven't decided on a good solution given the constraint of backwards compatibility and future proofing. I'll see about providing easier direct access to the gentoypes for now.

**Comment by brentp** [comment]
Hi, I have added access to the genotypes. It would be great if you could try this out and give feedback. Copying from the commit message, it works such that:

2-samples with genotypes 0/1  1|2 would result in a .genotypes of
`[[0, 1, False], [1, 2, True]]`

**Comment by wdecoster** [comment]
This appears to work fine. I assume genotype = -1 means no call was made. But I saw that the list is then [-1, False]. To me it would make more sense to have [-1, -1, False], but perhaps that's only important when you explicitly query for the phasing status (IndexError).

**Comment by brentp** [comment]
The length -1 indicates the ploidy, so a triploid genotype of `0/1/0` would have `[0, 1, 0, False]`.

You can always access the phase using index `-1`

**Comment by wdecoster** [comment]
Right, make sense!
