### ISSUE TITLE
MacOS ARM wheels broken?

### ISSUE THREAD

**Issue by jeromekelleher** [brentp/cyvcf2#305]
It looks like the binary wheels for Mac ARM builds is broken somehow. Basically we get symbol missing problems on import:

```
  from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
39
E   ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/cyvcf2/cyvcf2.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_bcf_float_missing'
```

I'm afraid I don't have a mac, so I can't help any further.

Some downstream reports:

- https://github.com/sgkit-dev/sgkit/issues/1220
- https://github.com/sgkit-dev/bio2zarr/pull/216

**Comment by brentp** [comment]
@graphenn do you have an idea about this?

**Comment by graphenn** [comment]
I don't have a Mac either. Additionally, the GitHub action can't test with macOS ARM. We need someone with this environment to assist.

**Comment by jeromekelleher** [comment]
@hyanwong or @tomwhite - would either of you be able to replicate? I think this is going to hit us downstream so it's would be great if we could track down the issue and hopefully fix the wheels.

**Comment by hyanwong** [comment]
I can replicate this on my M2 when installing cyvcf2 via pip (python 3.10, 3.11, and 3.12).

I have cyvcf2 working via another route. I'll see if I can figure out how I did that, and post here.

**Comment by hyanwong** [comment]
I can get a working cyvcf2 by compiling via `pip --no-binary=cyvcf2`. This requires both `autoconf` and `automake`. Make sure you `python -m pip uninstall cyvcf2` first if you have previously installed a non-working version:

```
mamba install automake autoconf
python -m pip install cyvcf2 --no-binary=cyvcf2 
```

**Comment by jeromekelleher** [comment]
Looking at the wheel building, it seems like we're cross-compiling for ARM on a macos-12 host. Would it be simpler to use the newer macos-14 GitHub actions runner and compile natively?

**Comment by jeromekelleher** [comment]
Or maybe use [cibuildwheel](https://github.com/pypa/cibuildwheel) directly? I don't know what the history of the wheel building process is here, sorry if we're going over old ground!

**Comment by hyanwong** [comment]
Is this something that cyvcf2 should sort anyway? It seems bad that I can `pip install cyvcf2` using a native wheel and it won't work. Should I report it as an issue on the cyvcf2 GH repo?

**Comment by graphenn** [comment]
> Looking at the wheel building, it seems like we're cross-compiling for ARM on a macos-12 host. Would it be simpler to use the newer macos-14 GitHub actions runner and compile natively?

Yes, the new macos-14 action runner makes it much easier. I create a PR for changing macos ARM to this runner.
#306

@hyanwong Could you test with the building wheel? https://github.com/graphenn/cyvcf2/actions/runs/9229532344
artifact-cp3xx-macosx_arm64

**Comment by brentp** [comment]
I pushed a new tag for this with the fix from @graphenn . [v0.31.0](/brentp/cyvcf2/releases/tag/v0.31.0)

**Comment by jeromekelleher** [comment]
Confirmed packages are working on macos-14 GitHub Action runner! Thanks very much!

**Comment by brentp** [comment]
:partying_face: thanks @graphenn

**Comment by jmarshall** [comment]
Sounds a lot like you were running into a similar problem to pysam-developers/pysam#1231, which we too worked around by ensuring we were compiling on e.g. ARM macOS rather than cross-compiling from a different architecture.
