### ISSUE TITLE
Stripping of quotation marks in VCF header description

### ISSUE THREAD

**Issue by juliangehring** [brentp/cyvcf2#33]
`header_iter` keeps the double quotation marks of the original VCF description:

Example taken from `test.vcf.gz`:
>  {'HeaderType': 'INFO', 'Description': '"Mean of all GQ values"', 'Type': 'Float', 'Number': '1', 'ID': 'GQ_MEAN'}
> {'HeaderType': 'FORMAT', 'Description': '"Allelic depths for the ref and alt alleles in the order listed"', 'Type': 'Integer', 'Number': 'R', 'ID': 'AD'}

Since the data is represented as a string in cyvcf2/python anyway, there should be no need to keep them. Should `header_iter` strip the quotation marks automatically, i.e. return 'Mean of all GQ values' rather than '"Mean of all GQ values"'?

**Comment by brentp** [comment]
Yes, it seems like it should strip. Can you open a PR? Otherwise, I'll get to this wednesday.

**Comment by juliangehring** [comment]
I don't think I can propose a change for this before next week.

**Comment by juliangehring** [comment]
But it also does not strike me as an urgent issue, since one can still to the stripping manually.
