### ISSUE TITLE
write slim VCF?

### ISSUE THREAD

**Issue by sigven** [brentp/cyvcf2#34]
Hi,

Would it be possible to use cyvcf2 to skip particular VCF header fields (i.e. altering the VCF template) when writing records? It seems it can add headers, but I could not figure out to set existing fields to NULL.

best,
Sigve

**Comment by brentp** [comment]
I forgot to follow up on this, I think I could support del variant.INFO['key']. I'll try to have a look at adding that soon. Please ping this if I forget. :(

**Comment by brentp** [comment]
I just pushed a change that lets you delete keys as proposed. Let me know any issues or comments.
