### ISSUE TITLE
variant.ID returns binary string

### ISSUE THREAD

**Issue by NeillGibson** [brentp/cyvcf2#38]
Hi Brent, 

Thank you for the very nice and useful htslib wrapper cyvcf2. 

When I parse a VCF file with cyvcf2 and try to print the ID assigned to the variant I get printed a binary string. 

E.g. 
```
reader = VCF("my_file.vcf.gz")
variant = next(reader)
print(variant.ID)

b'myID123456789'
```

Is this the intended behavior, or does this depend somehow on my input vcf or python version?
I am using python3.4 .  Both cyvcf2 version 0.6.5 and 0.7.0 give me the binary string for the ID.

Decoding the binary string before printing solves my issue but it would be nicer if that wasn't necessary.
```
print(variant.ID.decode('ascii'))

'myID123456789'
```

Thank you. 

Neill

**Comment by brentp** [comment]
I'd accept a pull request that uses the helper function from_bytes the convert to a string.

Otherwise, I'll get to this soon.

**Comment by NeillGibson** [comment]
I'll have a look but I am not sure my understanding of cython is good enough.  variant.Filter seems to have the same issue btw.

**Comment by brentp** [comment]
I just pushed a change that fixes this. It will be out in the next release.

**Comment by NeillGibson** [comment]
Thank you Brent!
