### ISSUE TITLE
Subset variants for samles of interest

### ISSUE THREAD

**Issue by NeillGibson** [brentp/cyvcf2#39]
Hi Brent, 

I am not sure how feasible this is and if this is something that cyvcf2 is meant to do. 
But at least I can ask. 

Would it be possible to subset samples in cyvcf2? 

The same functionality as that `bcftools view -s sample1,sample2` does? Including updating the AN and AC INFO values? 

Thank you.

**Comment by brentp** [comment]
This is already possible. Just send a list to the 'samples'  argument to the VCF constructor.

**Comment by NeillGibson** [comment]
Hi Brent, 

Thank you for the information. Using the samples argument of the VCF constructor does indeed only read in specified samples. 

However the AC and AN values are not updated. These are still the original value. 

```
reader = VCF("my.vcf.gz", samples=['Sample1', 'Sample2'])
variant = next(reader)
variant.INFO["AN"]
>>>56 
variant.INFO["AC"]
>>>34
print(str(variant))
Chr_07  129    .    G       C       686.61  PASS    AC=34;AF=0.607143;AN=56 GT:AO:DP:GQ:PL:QA:QR:RO   0/0:1:11:39:0,11,206:30:251:10  1/1:1:1:0:22,3,0:31:0:0
```

Is there a way to force recalculation of the AC and AN values when only reading in a few samples? 
I tried to look in the documentation and the code but can't find any information on if this is possible. 

Or can I myself set the values for these INFO fields?
The INFO setter mentions that only string can be set, not integers or list of integers
https://github.com/brentp/cyvcf2/blob/85e89acc114de61c2d043af79dbb52259cb9a4b5/cyvcf2/cyvcf2.pyx#L1758

```
 def __setitem__(self, key, value):
        # only support strings for now.
```

Thank you.
