### ISSUE TITLE
 can't extract region without tabix or csi index

### ISSUE THREAD

**Issue by hrora** [brentp/cyvcf2#43]
Hi there,
I followed the cyvcf2 code below, using my unzipped "mpg.snv.vcf" or "mpg.div.vcf" files but I got the error saying: "can't extract region without tabix or csi index"

1 import cyvcf2
2 import numpy as np
3 vcf = cyvcf2 . VCF ( path )
4 sample_counts = np. zeros (len (vcf . samples ), dtype
= float )
5 for variant in vcf(" chr1 :229993 -329993 "):
6 if variant . is_indel : continue
7 if variant . QUAL < 10: continue
8 depths = variant . format ("AD") # get all
depths .
9 sample_counts [( depths [:, 1] > 10) & ( variant
. gt_types == vcf .HET )] += 1
10 print (zip ( vcf . samples , sample_counts ))

I also tried with  "mpg.snv.vcf.gz.tbi"  file and got "Exception: bad path" error. 
What am I doing wrong?

thanks

**Comment by brentp** [comment]
if you give it the path ""mpg.snv.vcf.gz" and ""mpg.snv.vcf.gz.tbi" exists it will work.

**Comment by hrora** [comment]
This is what I use:

import cyvcf2
import numpy as np

snv500A = ('55_500A.mpg.snv.vcf.gz.tbi')
vcf = cyvcf2.VCF ('snv500A')

sample_counts = np. zeros (len (vcf . samples ), dtype = float )
for variant in vcf(" chr22 :36265140 -36267531 "):
	if variant . is_indel : continue
	if variant . QUAL < 10: continue
	depths = variant . format ("AD") # get all depths .
	sample_counts [( depths [:, 1] > 10) & ( variant. gt_types == vcf .HET )] += 1
	zippedsnv500A = zip ( vcf . samples , sample_counts)	
print ( zippedsnv500A )

**Comment by brentp** [comment]
to open the vcf you need:

```
snv5A = '5_A.mpg.snv.vcf.gz'
vcf = cyvcf2.VCF (snv5A)
```

note that you don't want to quote `snv5A` or it will look for a file of that name.
