### ISSUE TITLE
how can we accomplish something like this ?

### ISSUE THREAD

**Issue by snashraf** [brentp/cyvcf2#45]
for i in data:      
                 arrChr = i.split("\t")[0]
                 arrVal = i.split("\t")[1]
                 print (arrChr, arrVal)
                 for v in vcf(arrChr:arrVal-arrVal):
                        print (v.INFO["AF"])

above is throwing SyntaxError: invalid syntax error. 

Any idea how to query like this dynamically?

**Comment by brentp** [comment]
```
for v in vcf("%s:%d-%d" % (chrom, int(start), int(end))):
     print v
```
