### ISSUE TITLE
CSI index not recognized / used with BCF.gz files

### ISSUE THREAD

**Issue by NeillGibson** [brentp/cyvcf2#46]
Hi Brent, 

We store our larger variant callings files in BCF.gz format. Because of the binary format bcftools queries on those files are much faster then on the same file in vcf.gz format. 

When trying to select variants based on positions from that file cyvcf2 throws an error about a missing tbi index. 
```
from cyvcf2 import VCF
reader = VCF("my_variant_calling.bcf.gz")
reader("Chr_00:252")
variant = next(reader("Chr_01:252"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cyvcf2/cyvcf2.pyx", line 355, in __call__ (cyvcf2/cyvcf2.c:9727)
AssertionError: error loading tabix index for b'my_variant_calling.bcf.gz'
```

A CSI index file already exists from that file, and `bcftools view -r Chr_01:252` works. 

It is not possible to create a TBI index for a BCF file:
```
bcftools index --tbi my_variant_calling.bcf.gz
[Warning] TBI-index does not work for BCF files. Generating CSI instead.
[E::main_vcfindex] the index file exists. Please use '-f' to overwrite.
```

Would it be possible to have cyvcf2 use the CSI index with BCF files? cyvcf2 is able to loop over the variants in the BCF file, so it understand BCF, just not the CSI index it seems. 

Otherwise one would have to duplicate BCF files to VCF to make custom region queries possible via cyvcf2. 

Thank you.

**Comment by brentp** [comment]
how is your bcf.gz created? Is it just standard bcf (which is compressed) with a .gz extension?

can you share a small bcf.gz file I can test on?

**Comment by NeillGibson** [comment]
Hi Brent, thank you for the quick reply. 

The bcf.gz has been created by converting a vcf.gz file to bcf.gz file using bcftools:
 `bcftools view -O b -o my_variant_calling.bcf.gz my_variant_calling.vcf.gz` 

I tested this issue on a second BCF created in the same way but with less downstream processing. 

For that second vanilla bcf file and I get the same error, so I am thinking it should hold for all bcf files created by the above command? 

I can probably send you a minimal and clean BCF file tomorrow for reproducing the issue.

**Comment by brentp** [comment]
ok. so the bcf you are creating is just a bcf. the .gz is superfluous and cyvcf2 will work fine if you don't have the .gz extension. I'll make it more tolerant to this type of naming, but you can make it work now by removing the .gz suffix.

**Comment by NeillGibson** [comment]
Ah ok many thanks. I did not know what the expected extension was for un/compressed bcf.

I can confirm that cyvcf2 can do the range query via the CSI index when the just has bcf as the extension.

**Comment by mbhall88** [comment]
I am having the same issue. I don't really want to have to rename all of my files. @brentp do you have any idea of when you might be able to implement seamless support of `.bcf.gz`?

**Comment by brentp** [comment]
I pushed a fix for this.
