### ISSUE TITLE
gt_types returns empty list after using set_samples

### ISSUE THREAD

**Issue by tobiasmarschall** [brentp/cyvcf2#49]
Hi Brent,

I just tried to use `set_samples` and `gt_types` in combination. Here's an example VCF:
```
##fileformat=VCFv4.1
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG004	HG003	HG002
chr1	60906167	.	G	A	.	PASS	.	GT	0/1	0/1	0/0
```

And here's what I did:
```
>>> from cyvcf2 import VCF
>>> vcf = VCF('trio.vcf', gts012=True)
>>> for variant in vcf:
...     print(variant.gt_types)
... 
[W::vcf_parse] contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[1 1 0]
>>> vcf = VCF('trio.vcf', gts012=True)
>>> vcf.set_samples('HG003')
>>> for variant in vcf:
...     print(variant.gt_types)
... 
[W::vcf_parse] contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[]
```
Why am I getting an empty list? Is this a bug or am I doing something wrong?

**Comment by brentp** [comment]
Try:
```
vcf = cyvcf2.VCF('t.vcf', gts012=True, samples=['HG003'])
```

**Comment by brentp** [comment]
I'll leave this ticket open as a reminder to make set_samples private or to re-init the header when it is run.

**Comment by brentp** [comment]
I just pushed a fix so that your usage will work fine. You can either update or use the `samples` kwarg in the constructor as in my example above.

thanks for reporting.

**Comment by tobiasmarschall** [comment]
Just tried the latest version. Works as expected. Thanks a lot for fixing this so quickly!
