### ISSUE TITLE
Implement methods for modifying the API - Adding filters

### ISSUE THREAD

**Issue by danielecook** [brentp/cyvcf2#5]
Following up on https://github.com/brentp/cyvcf2/pull/4, It would be nice to be able to edit the header of vcf files in addition to adding/editing filter/info/format data. The implementation might look like this, although you may know of a better way:

```
v = VCF("my_vcf.vcf.gz")
# Here I am adding a format field to mark snps as validated
v.header.INFO["VALID"] = {"Number": 1, "Type":"Flag", "Description": "flag indicating a snp/indel has been validated"}

for variant in v:
    if variant in validated_variants:
        variant.INFO["VALID"] = True

# Adding a filter
v.header.FILTER["low_complexity_region"] = {"Number": 1, "Type":"Flag", "Description": "flag indicating a snp/indel observed in a low complexity region."}

for variant in v:
    if variant in low_complexity_regions:
        variant.FILTER.append("low_complexity_region") # Appends to existing filters
```

I also have been having trouble accessing VCFs by region. I can open as a separate issue. Python crashes when I attempt to do something like:

```
v = VCF("test.vcf.gz", "I:1-10000")
```

**Comment by brentp** [comment]
for accessing by region, you need:
```Python
vcf = VCF("test.vcf.gz")
for variant in vcf("1:1-1000"):
     print(variant)
```

thanks for opening. I'll try to get to this in the new year.

**Comment by brentp** [comment]
Hi @danielecook and @chapmanb I have implemented this in 0.2.5 which is now on pypi and pulled into bioconda. The API isn't the best, but it's usable. It lets you add filters, formats, and infos to the header.
See the tests for examples and let me know any questions.

**Comment by chapmanb** [comment]
Brent -- awesome thanks for jumping on this so quickly. This is a big help, much appreciated.

**Comment by brentp** [comment]
sure. let me know any other feature requests. I'd like this to be a popular lib for python+vcf.

**Comment by danielecook** [comment]
@brentp - Awesome! I do have another idea, I will file as an issue.
