### ISSUE TITLE
Update format and filter field in header

### ISSUE THREAD

**Issue by juliangehring** [brentp/cyvcf2#50]
It would be a great extension to have the `VCF.update` function also allow the updating of format and filter fields in the VCF header; perhaps with a similar interface as the VCF.add_{info,filter,format}_to_header` functions. Or at least I have not been able to achieve this with the existing functionality, and there may already a clever way that I may have missed.

**Comment by brentp** [comment]
hi, could you give a snippet of what you are trying to do? 

there's an example of setting the format fields here: https://github.com/brentp/cyvcf2/blob/master/cyvcf2/tests/test_reader.py#L540

**Comment by brentp** [comment]
I'm going to close, but feel free to open if you have more detail or if this continues to be a problem.
