### ISSUE TITLE
Install fails on centos

### ISSUE THREAD

**Issue by robinandeer** [brentp/cyvcf2#52]
Hi,

the conda release (bioconda) seems to be lagging behind a little and I wanted to try installing using pip. However, I run into a "gcc" error:

```
...
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ihtslib -Icyvcf2 -Isetup-requires/numpy/core/include -I/home/glsai/miniconda2/envs/cyvcf2-test/include/python3.6m -c htslib/vcfutils.c -o build/temp.linux-x86_64-3.6/htslib/vcfutils.o
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ihtslib -Icyvcf2 -Isetup-requires/numpy/core/include -I/home/glsai/miniconda2/envs/cyvcf2-test/include/python3.6m -c htslib/tbx.c -o build/temp.linux-x86_64-3.6/htslib/tbx.o
  In file included from htslib/tbx.c:33:
  htslib/htslib/bgzf.h:35:18: error: zlib.h: No such file or directory
  In file included from htslib/tbx.c:33:
  htslib/htslib/bgzf.h:69: error: expected specifier-qualifier-list before ‘z_stream’
  error: command 'gcc' failed with exit status 1
```

I'm running on:

```
Linux version 2.6.32-642.11.1.el6.x86_64 (mockbuild@c1bm.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Fri Nov 18 19:25:05 UTC 2016
```

I don't have sudo access on this cluster so I can't install dev packages so easy. Would you recommend installing using conda in this case? Numpy (the only dependency?) seems to install fine btw 🙂

**Comment by brentp** [comment]
It looks like you don't have zlib installed, so you'll need the zlib libraries and headers. Then it should work.

**Comment by robinandeer** [comment]
Yes that sounds correct. Since I don't have root access I can't install those tho.
I will do some more Google:ing

**Comment by brentp** [comment]
Noted. I'll update the bioconda recipe next week.

**Comment by robinandeer** [comment]
🥇

**Comment by brentp** [comment]
it's on it's way: https://github.com/bioconda/bioconda-recipes/pull/4679/files
