### ISSUE TITLE
Odd genotype resolution when with a single missing allele

### ISSUE THREAD

**Issue by indraniel** [brentp/cyvcf2#54]
There seems to be a misclassification when resolving a genotype containing a single missing allele.  Genotypes of `0/.`, `./0`, `1/.`, or `./1` seem to be classified as heterozygous ("HET" or id: 1) instead of "UNKNOWN" (or id: 2).  Is this supposed to be the intended behavior for cyvcf2?

Shown below is an example test case I've constructed.

Test VCF File: `test-cyvcf2-genotype-call.v2.vcf.gz`

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##ALT=<ID=*:DEL,Description="Represents any possible spanning deletion allele at this location">
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=MT,length=16569>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  foo1    foo2    foo3    foo4    foo5    foo6    foo7    foo8
MT      310     .       T       C       1.83648e+07     PASS    .       GT      0/0     1/1     0/1     1/0     1/.     ./1     0/.     ./0
```

Python genotype calling code:

```python
#!/usr/bin/env python

from __future__ import print_function
import os

from cyvcf2 import VCF
import numpy as np

testvcf = os.path.join(os.environ['HOME'], 'test-cyvcf2-genotype-call.v2.vcf.gz')

vcf = VCF(testvcf)
variant = next(vcf)

print('variant.gt_bases: {}'.format(variant.gt_bases))
print('variant.gt_types: {}'.format(variant.gt_types))
```

And the corresponding output:

```
variant.gt_bases: ['T/T' 'C/C' 'T/C' 'C/T' 'C/.' './C' 'T/.' './T']
variant.gt_types: [0 3 1 1 1 1 1 1]
```

Shouldn't the above `variant.gt_types` be `[0 3 1 1 2 2 2 2]` ?

**Comment by brentp** [comment]
This is a limitation of how gt_types are represented. Does the presence of a "." mean it's unknown? or it's het? you can make a case for either.

**Comment by indraniel** [comment]
Could this be made configurable in some way?

**Comment by indraniel** [comment]
I attempted to make treating these missing allele interpretations a "configurable feature" to `cyvcf2`.  See [pull request 55][0].

Let me know if I need to address any further issues or changes.

[0]: https://github.com/brentp/cyvcf2/pull/55
