### ISSUE TITLE
How to check for presence of INFO or FORMAT fields in VCF that have the same ID?

### ISSUE THREAD

**Issue by NeillGibson** [brentp/cyvcf2#56]
Hi Brent, 

I know how to check for the presence of a VCF attribute by ID:

```
from cyvcf2 import VCF
reader = VCF("my.vcf.gz")
"AC" in reader
True
```

Sometimes I need to check for the presence of a VCF FORMAT attribute that also has a INFO attribute with the same name.  For example INFO/RO and FMT/RO:

```
##INFO=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count, with partial observations recorded fractionally">
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
```

In this case the FMT/RO attribute has been removed but the INFO/RO attribute is still present.  

If I just check on the ID I get back true:
```
from cyvcf2 import VCF
reader = VCF("my.vcf.gz")
"RO" in reader
True
```

I would like to be able to specifcly check on the INFO and FORMAT attribute:
```
from cyvcf2 import VCF
reader = VCF("my.vcf.gz")
"INFO/RO" in reader
True
"FMT/RO" in reader
False
```

Currently this gives back `False` twice since the INFO and FMT prefix is not understood. 

Is it already possible to check specificly for presence of INFO and FMT attributes? Or would it be possible to add this functionality? 

I guess it's related to this function:
https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L457

Thank you!

**Comment by brentp** [comment]
you can do this with `vcf.header_iter` which gives you an HREC object. (https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L1719)
something like (untested):
```Python

for rec in vcf.header_iter():
    d = rec.info()
    if d['Type'] != "FORMAT": # or "INFO" or "FILTER"
        continue
    if d['ID'] == myid:
        print("found")
        break
```

**Comment by brentp** [comment]
let me know if that works for you. we can think about how to encapsulate this into a nicer method.

**Comment by NeillGibson** [comment]
Hi Brent. Thank you for the code snippet. 

However there does not seem to be a way to get the ID field of a record returned by `vcf.header_iter()`.

Is there another way to get access to the combination of the header type and the ID field? Thank you. 

```
for rec in reader.header_iter():
...     print(rec.info())
...
{'HeaderType': 'GENERIC'}
{'HeaderType': 'FILTER'}
{'HeaderType': 'FORMAT'}
{'HeaderType': 'FORMAT'}
{'HeaderType': 'INFO'}
{'HeaderType': 'INFO'}
etc.
```

None of the methods available that I tried return the ID field of the header records.
```
for rec in reader.header_iter():
...     rec.info()['ID']
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
KeyError: 'ID'
```

```
 for rec in reader.header_iter():
...     rec.__getitem__('ID')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "cyvcf2/cyvcf2.pyx", line 1708, in cyvcf2.cyvcf2.HREC.__getitem__ (cyvcf2/cyvcf2.c:34129)
KeyError
```

```
for rec in reader.header_iter():
...     rec.__getattribute__('ID')
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'cyvcf2.cyvcf2.HREC' object has no attribute 'ID'
```

```
for rec in reader.header_iter():
...     rec.type
...
'GENERIC'
'FILTER'
'FORMAT'
'FORMAT'
'INFO'
'INFO'
etc.
```

**Comment by brentp** [comment]
I just pushed a fix for this. I assume you were using python 3? rec.info() should now return the full dict.
re-open if you still have troubles.
