### ISSUE TITLE
Add string type field in FORMAT

### ISSUE THREAD

**Issue by shubhamsaini** [brentp/cyvcf2#59]
Is it possible to add a non-numeric FORMAT field?

For example, I'm trying to add a field called ZZ, which is similar to GT. So my VCF would look like:
`GT:ZZ 0|1:p|q`

**Comment by brentp** [comment]
this isn't possible right now. I'll try to add this next week.

**Comment by brentp** [comment]
sorry for the delay. I did try adding this, but turned out to be harder than expected. I'll have another look if there is still a need for this.

**Comment by shubhamsaini** [comment]
I don't need this urgently. This is a beneficial feature none the less as no other library/tool currently supports this, so you might want to keep this on your to-do list. Thanks!

**Comment by brentp** [comment]
ok. I'll get it implemented. thanks for following up.

**Comment by danielecook** [comment]
I also would definitely make use of this feature!

**Comment by everestial** [comment]
I may be using this method/feature sometime soon.

**Comment by ChristopheLegendre** [comment]
Hi cyvcf2 team,

I am also _very much_ interested in that feature. 
Adding **sample-specific** data to the Format field for each sample is really needed. I, _For instance_, need to currently add new calculated fields to the format field of each sample in my vcf; these fields will be use later for filtering by collaborators.

Is there any update on that implementation?  I have not seen any update in the documentation.
Can we have a method that adds data to the column 9 and beyond?

For instance, I would like to add the field 'MF' to the FORMAT column and the MF value to each sample from column 10 and beyond; it could be as:
`v.FORMAT['MF'] = [ValueForSample1, ValueForSample2, ValueforSampleX, ..., ValueForSampleN ]`
where v is the Variant obj `cyvcf2.cyvcf2.Variant`.
The implementation would take care of adding each value to the sample column in the variant record.

Thanks.

**Comment by brentp** [comment]
i tried to do this a while back, but I never figured it out. I'd accept a pull-request of course. Otherwise, I'll have another look in mid July.

**Comment by ChristopheLegendre** [comment]
@brentp  
Hi Brent,
Thanks for your reply.
I deal with **big** vcf files (reading, filtering, extracting and modifying vcfs). I really like the **fast** tool you provide here to do so.
_Unfortunately_, my knowledge of python is quite rudimentary, far from the level needed here for that kind of work.

When you have your other look at the possibility of adding feature(s) that modify the **FORMAT** **fields** (adding TAG+VALUE to each sample has been so far the most requested feature), I will be glad to test it out.

**_PS_**: just to add further info to my previous example
`v.FORMAT['MF'] = [ValueForSample1, ValueForSample2, ValueforSampleX, ..., ValueForSampleN ]`
where v is the Variant obj cyvcf2.cyvcf2.Variant.
The real values in the record and vcf file would then be:
   DP:FDP:SDP:**MF**   82:0:0:**vMF1**      48:1:0:**vMF2** 

...  and we will add the new field to the vcf header using the function you already implemented, 
`add_format_to_header(self, adict)`

Thanks again for considering community's request.

**Comment by LiterallyUniqueLogin** [comment]
Hi there,

I also need this functionality for my tool to adopt cyvcf2 as the underlying library. I'm willing to look at writing this code myself, but I'd need some pointers. Where in the code base would this slot in? What were the issues that you previously ran into that would need to be overcome for this to work?

**Comment by brentp** [comment]
Hi, you can look in cyvcf/cyvcf2.pyx in the functoin `set_format`.
and you can see how i handle this in hts-nim [here](https://github.com/brentp/hts-nim/blob/master/src/hts/vcf.nim#L262-L282)

basically, you accept a list of strings where len(list) == n_samples. Then you find the longest string in that list of strings (`lmax`).
then you create a single string of length `lmax * n_samples`. Then you fill that string with zeros. (you can use calloc in cyvcf2) then you set the respective entries in there.

**Comment by LiterallyUniqueLogin** [comment]
If I'm allocating a string, am I responsible for deallocating it after the call to `bcf_update_format_char`? That seems to be what the nim code is doing, but I wanted to double check.

**Comment by brentp** [comment]
if you malloc, yes, you must free.

**Comment by LiterallyUniqueLogin** [comment]
Sorry for the delay, the internet has been out where I live. I attempted to write the feature and its tests, but I have not been able to run the tests because of environment issues. After a successful local install, I run  `python setup.py test` and get the error
```
ImportError: /projects/ps-gymreklab/jmargoli/cyvcf2/cyvcf2/cyvcf2.cpython-37m-x86_64-linux-gnu.so: undefined symbol: libdeflate_free_decompressor
```
I work in an Ananconda environment, any idea what I have to do to get setup.py test to see the header files in the environment's include directory?

Alternatively, I can just share my code with you and you can determine next steps for us from there.

**Comment by brentp** [comment]
you can install libdeflate, but that should be installed if you conda installed cyvcf2.
if you open the PR, I can take it from there.

**Comment by LiterallyUniqueLogin** [comment]
With the PR merged this can be marked as closed if you'd like.

**Comment by Titorat** [comment]
Apologize for re bringing this up. 
How the code for adding a new Format TAG with value will look like? Also can I choose the position? 
I tried different things with set_format with no luck, thanks!

**Comment by brentp** [comment]
Hi, you can see the examples here: https://github.com/brentp/cyvcf2/blob/main/cyvcf2/tests/test_reader.py#L771-L787
you can not set the order, it will always add a new field at the end.
Note that you must add to the header (as in those tests) before using it in set_format if it's not alreaady present.
