### ISSUE TITLE
Enable access to genotypes using __get__ for variant class

### ISSUE THREAD

**Issue by danielecook** [brentp/cyvcf2#6]
Support for genotype iteration and access to genotypes by sample name would be very useful. 

For example:

```
vcf = VCF("test.vcf.gz")
for line in vcf:
    # FORMAT: = GT:DP
    # return {"GT": 3, "DP": 50}
    line["sample_name"] # return {"GT": 3, "DP": 50}
```

Alternatively, the above could stay inline with the properties defined in the variant class, returning something like:
`{"gt_bases","T", "gt_quals":20, "is_snp": True, etc.}`

Support for iteration would also be very useful:

```
for line in vcf:
    for call in line: 
         # Return dict of sample name + format params.
```

Although it is not essential, the ability to add/alter call information would be great as well.

Thanks for the hard work on this project. It is an immense help and I am integrating it within some python projects I hope to distribute.

**Comment by brentp** [comment]
yeah, I think being able to get a Sample() object given a name would be useful.
For now, everything is optimized to return a numpy array for fixed attributes.
I'll think about how to do this, but I think `line["sample_name"]` would return some kind of Sample object and then if you wanted, you could do `d = dict(sample_obj)` as is possible for INFO now.

**Comment by danielecook** [comment]
I agree with using an object. One suggestion would be to name the class `call` or `_call` as is done in [pyVCF](https://github.com/jamescasbon/PyVCF/blob/0e136b63fd53b6468ed4f7bf7bc04f5320116ece/vcf/model.py#L13)?

**Comment by danielecook** [comment]
Thanks for implementing this. I'm having trouble accessing some format fields. Specifically - it looks like string fields are the issue. This is the error I get:
```
ValueError: data type must provide an itemsize
```
When I try to access the `GT` column and the `FT` column in a VCF. 

Any idea what might be the cause?

Thanks!

**Comment by brentp** [comment]
this is implemented via .format method on variant.
