### ISSUE TITLE
slow speed of vcf.samples

### ISSUE THREAD

**Issue by liqg** [brentp/cyvcf2#61]
Hi Brentp,
cyvcf2 is very good, thanks for your effort!
But I found the vcf.samples is very slow in this code:
The test.vcf is just a part of 1000k genome file (~1000 head lines )with ~2500 samples.
```python
from cyvcf2 import VCF
vcf = VCF("test.vcf")
for variant in vcf:
    for i in range(0,len(vcf.samples)):
        print vcf.samples[i]
```
However, when I store vcf.samples as a new python variable, it is fast.
```python
from cyvcf2 import VCF
vcf = VCF("test.vcf")
samplenames = vcf.samples
for variant in vcf:
    for i in range(0,len(vcf.samples)):
        print samplenames[i]
```
So, I infer there may be some excessive behaviour when using vcf.samples.

**Comment by brentp** [comment]
`cyvcf2` does not cache the result. It is indeed faster to get it outside of the loop. I don't consider this a bug, but would gladly accept a pull-request to document this behavior.
