### ISSUE TITLE
fail to install 

### ISSUE THREAD

**Issue by hsiehph** [brentp/cyvcf2#63]
Hi there,

I am running into an installation error (shown as below) and hopefully you can point me to some directions to resolve it. This is an attempt to install cyvcf2 at user's home directory on a RHEL6 (cluster) system and under anaconda v2.3.0 

Thanks!

==========================

$ python setup.py install --prefix=~/.local

    /net/gs/vol3/software/modules-sw/gcc/4.9.1/Linux/RHEL6/x86_64/bin/gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/net/gs/vol3/software/modules-sw/samtools/1.1/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/bwa/0.7.3/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/boost/1.58.0/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/htslib/1.3.2/Linux/RHEL6/x86_64/include -I/net/gs/vol3/software/modules-sw/tabix/0.2.6/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/zlib/1.2.6/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/R/3.2.1/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/gcc/4.9.1/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/gmp/5.0.2/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/mpfr/3.1.0/Linux/RHEL6/x86_64/include/ -I/net/gs/vol3/software/modules-sw/mpc/0.8.2/Linux/RHEL6/x86_64/include/ -fPIC -Ihtslib -Icyvcf2 -I/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python3/lib/python3.4/site-packages/numpy/core/include -I/net/eichler/vol6/software/modules-sw/anaconda/2.3.0/Linux/RHEL6/x86_64/envs/python3/include/python3.4m -c htslib/cram/cram_io.c -o build/temp.linux-x86_64-3.4/htslib/cram/cram_io.o
    htslib/cram/cram_io.c:2158:17: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static unsigned get_int_threadid() {
                     ^
    htslib/cram/cram_io.c: In function ‘cram_set_voption’:
    htslib/cram/cram_io.c:4481:10: error: ‘CRAM_OPT_LOSSY_NAMES’ undeclared (first use in this function)
         case CRAM_OPT_LOSSY_NAMES:
              ^
    htslib/cram/cram_io.c:4481:10: note: each undeclared identifier is reported only once for each function it appears in
    error: command '/net/gs/vol3/software/modules-sw/gcc/4.9.1/Linux/RHEL6/x86_64/bin/gcc' failed with exit status 1

**Comment by brentp** [comment]
can you show the full output?

also, since you're using conda, why not just do

```
conda install -c bioconda cyvcf2
```
?

**Comment by hsiehph** [comment]
Hello,

I tried condo install earlier and was having some permission issue on our cluster, but was able to successfully install cyvcf2 with helps by our IT team.

Thanks for your reply anyways!
