### ISSUE TITLE
Also return contig/chromosome sizes from the seqnames function.

### ISSUE THREAD

**Issue by NeillGibson** [brentp/cyvcf2#64]
Hi,

Would it be possible to also return contig/chromosome sizes from the seqnames function?

Currently a list of contig/chromosome names is returned. 
```
from cyvcf2 import VCF
reader = VCF("my.vcf.gz")
reader.seqnames
['Chr_00', 'Chr_01', 'Chr_02', 'Chr_03', 'Chr_04', 'Chr_05', 'Chr_06', 'Chr_07', 'Chr_08', 'Chr_09']
```

To be even more sure that the VCF was made using the expected reference genome we would like to be able compare also on contig/chromosome size. Most VCF files have contig/chromosome size defined in the header. 

So than the seqnames function could return a dictionary. With None values if the contig/chromosome size was not defined in the VCF header.  
```
from cyvcf2 import VCF
reader = VCF("my.vcf.gz")
reader.seqnames
{'Chr_00': 12345,
 'Chr_01': 12345,
 'Chr_02': 12345,
 'Chr_03': 12345,
 'Chr_04': 12345,
 'Chr_05': 12345,
 'Chr_06': 12345,
 'Chr_07': 12345,
 'Chr_08': 12345,
 'Chr_09': 12345}
```

Thank you.

**Comment by brentp** [comment]
I have made it so you can access these via `reader.seqlens` you can, of course get a dictionary by zipping the seqnames and lens. please see the commit message for other changes that this required.

thanks for the idea.

**Comment by NeillGibson** [comment]
Ah many thanks for the quick implementation. Having to zip the seqnames and seqlens is fine. Thank you.
