### ISSUE TITLE
Distinguish missing values and PASS in FILTER column

### ISSUE THREAD

**Issue by sigven** [brentp/cyvcf2#67]
Hi,

It seems I am not able to make cyvcf2 distinguish between variant records with a passed FILTER value ('PASS') and those with a missing FILTER value ('.'). The rec.FILTER both returns 'None'. Is this by intent or am i missing something/doing something wrong? Thanks either way for very nice work!
best,
Sigve

**Comment by brentp** [comment]
Hmm, I think these are identical in htslib, if not the spec, no? I have assumed that the lack of a FILTER indicates PASS.

**Comment by sigven** [comment]
I have tried to figure out the same, the only thing I found in the VCF spec is that the '.' denotes a missing value. It's not a big deal, I merely think that explicit use of PASS appear more trustworthy. I am closing the issue for now.
