### ISSUE TITLE
Strange behaviour with mismatched types in INFO field

### ISSUE THREAD

**Issue by sndrtj** [brentp/cyvcf2#69]
Hi there,

I'm not sure whether this is a cyvcf2 issue or a htslib issue, or whether it's an issue at all, but I am encountering some strange behaviour when the type of an INFO field specified in the header does not match with the actual type in the field value. 

Consider the following VCF file:

```
##fileformat=VCFv4.1
##INFO=<ID=TEST,Number=.,Type=Integer,Description="Test info field">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=HQ,Number=2,Type=Integer,Description="Haplotype Quality">
##FILTER=<ID=PASS,Description="All filters passed">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
Artificial	100	.	A	T	100	PASS	TEST=0.05
Artificial	101	.	T	C	100	PASS	TEST=0.001004016064257028,0.001004016064257028
Artificial	102	.	A	G	100	PASS	TEST=5.45,10.0
```

The header field describes the `TEST` INFO field as a list of integers, but the records actually contain lists of floats. When parsing the INFO field, strange things happen:

```python
In [1]: from cyvcf2 import VCF

In [2]: reader = VCF("malformed.vcf")

In [3]: for record in reader:
   ...:     print(record.INFO.get("TEST"))
   ...:     
0
(0, -1260659708)
(5, 45)
```

Now, obviously the VCF header is not correct in this situation. Should cyvcf2 raise a warning or error when encountering such a situation?

**Comment by brentp** [comment]
hi, this does appear odd, but if you run `bcftools view` on that VCF (as I just tried), then you get those same integer values from bcftools. So, this not something that is broken in cyvcf2.
