### ISSUE TITLE
Enable zip and indexing from cyvcf

### ISSUE THREAD

**Issue by moonso** [brentp/cyvcf2#7]
Would it be possible to bgzip and create index from cyvcf?

**Comment by brentp** [comment]
I'll have a look into this tomorrow. The change would be that the writer would write bgzipped file if the extension was .gz

**Comment by moonso** [comment]
:+1: . Do you mean if the extension is not .gz? The problem I'm after is how to handle unzipped vcf:s...

**Comment by brentp** [comment]
it can already read unzipped vcfs, it just can do spatial queries on them.

**Comment by moonso** [comment]
Ok sorry about that, didn't check. It would still be nice to zip and create index from cyvcf2 though!
