### ISSUE TITLE
gt_types unpredictable

### ISSUE THREAD

**Issue by jessehoff** [brentp/cyvcf2#71]
i'm building a list of gt_types arrays, but it seems to misbehave depending on the region being queried. 

>F_chrm10 = '../nam-data/NAM_Chr10.vcf.gz'
H_vcf10 = VCF(F_chrm10,gts012=True)
vardict = {}
for v in H_vcf10('10:1800000-1815540'):
  >> vardict[v.ID]= v.gt_types

>print(vardict['S10_2261121'][:20])

[0 3 3 3 0 0 3 3 3 3 3 3 0 3 0 3 3 3 3 3]

bcftools view -r 10:1815438 NAM_Chr10.vcf.gz -H | head -c 80
[W::bcf_hdr_check_sanity] PL should be declared as Number=G
10      1815438 S10_2261121     C       T       .       PASS    .       GT      0/0     ./.     ./.     ./.     0/0     0/0     0/0     0/0     0/0     0/0     0

Also sometimes returns negative values 

Any ideas? some sort of malformation of the vcf would make sense.

**Comment by brentp** [comment]
hi, if you are saving them, you need to use:
```
vardict[v.ID]= np.array(v.gt_types)
```

to make a copy. otherwise, it's pointing at the underlying data which will go out of scope when the `v` object does. I'll leave this open as a reminder to document that caveat.

**Comment by jessehoff** [comment]
that worked, thanks.  I had figured out that I was not actually understanding how np makes copies,  but didn't know how to fix it!
