### ISSUE TITLE
Implement something similar to FastaVariant from pyfaidx?

### ISSUE THREAD

**Issue by daquang** [brentp/cyvcf2#74]
Hi, great software you have here. I was wondering if cyvcf2 has something similar to the FastaVariant class from pyfaidx? I need a way to efficiently draw sequences with SNPs replacing single letters in FASTA files. Does cyvcf2 have something like this handy?

**Comment by brentp** [comment]
I'm not sure I understand the functionality that you're asking for, but you could easily modify a fasta using [pyfaidx](https://github.com/mdshw5/pyfaidx) with the variants that you get from cyvcf2

IIUC, this is outside the scope of what cyvcf2 will do for you.

**Comment by daquang** [comment]
Gotcha. Yes, that was what I was looking for. For example, if a SNP in a VCF file were to change chr1:10000 from an A to a T, then I was hoping that if I were to fetch subsequence chr1:9990-10010, the returned subsequence would correctly reflect that single nucleotide change. Thank you for answering the question.

**Comment by brentp** [comment]
glad it helped. Yes, I think you can do this quite easily with cyvcf2 + pyfaidx.
