### ISSUE TITLE
record.samples throwing error

### ISSUE THREAD

**Issue by everestial** [brentp/cyvcf2#76]
I am getting error when trying to access `samples` from record. My code is:

    from cyvcf2 import VCFReader
    from cyvcf2 import VCF

    vcf_data = VCFReader('some.vcf')
        for record in vcf_data:
            contig = record.CHROM
            pos = record.POS
            ref_allele = record.REF

            #works fine until this code, then error comes
            print(record.samples)

            # I am trying to do
            for sample in record.samples: 
                sample_id = record.genotype(sample.sample)
                genotype_base = sample_id.gt_bases
                PG_value = sample['PG"]

**Error message:**

    Traceback (most recent call last):
        File "/home/everestial007/Haplotypes.py", line 127, in <module>
            print(record.samples)
    AttributeError: 'cyvcf2.cyvcf2.Variant' object has no attribute 'samples

But, while writing the code I can see `samples` attribute being activated after I type in `record`.

**Comment by brentp** [comment]
`samples` is an attribute on VCF, not on `Variant` I would also recommend to call it once before your loop and then re-use:
```
samples = vcf.samples

for variant in vcf:
   ...
```

**Comment by everestial** [comment]
Looks like things as have changed compared to how things were called in pyVCF. The cyvcf (python2 implementation) stays the same but this cyvcf2 had to be different, WHY?

I am not confused on how to call `gt_bases` for sample of samples.

    vcf_data = VCF("my_vcf.vcf")
    for record in vcf_data:
         samples = vcf_data.samples
         for sample in samples:
             genotype_base = sample.gt_bases

**Error message:**

    Traceback (most recent call last):
      File "/home/everestial007/PycharmProjects/stitcher/GW_phaseUsingRBphasedHaplotypes.py", line 150, in <module>
        genotype_base = sample_id.gt_bases
    AttributeError: 'str' object has no attribute 'gt_bases'


But, this works:

        for record in vcf_data:
            print('gt_bases: ', record.gt_bases)

So, is it safe to assume that `nested for - loop` i.e `for sample in samples` has been deprecated?

**Comment by brentp** [comment]
cyvcf2 is not compatible with pyVCF so you'll have to read the docs for cyvcf2. I maintained compatibility with cyvcf in many cases, but I made changes where it improved performance.

`vcf.samples` gives you a list of strings of sample names.

variant.gt_bases gives you a numpy array of strings where each index comes from the sample indicated by the same index in the `samples` array.
