### ISSUE TITLE
multiprocessing in cyvcf2

### ISSUE THREAD

**Issue by everestial** [brentp/cyvcf2#77]
I was wondering if there (already exits?) is a possibility of embedding multiprocessing within `cyvcf2` module. 

I know it is possible to introduce `multiprocessing/threading/pooling` using custom python script along with `cyvcf2`. But, having an internal class/function that can process multiple chromosomes at once (by adding an extra flag) would be a nice feature.

**Comment by brentp** [comment]
you can use multithreading (the gil is released by cyvcf2 where possible) or multiprocessing as you like. for now, it it outside of the scope of this library to support it internally.
