### ISSUE TITLE
Optionally allow VCF() to take file object as input rather than str filename

### ISSUE THREAD

**Issue by bjpop** [brentp/cyvcf2#78]
This would be handy if we want to read from stdin, for example.

**Comment by brentp** [comment]
there is another issue for this, but I never got around to implementing. for now, you can get STDIN by using "-" as the file name.

**Comment by MattOates** [comment]
I'm currently dealing with BytesIO like objects and don't have much choice given how our S3 handling code is setup to be all in memory. Any chance you can point me in the right direction for getting this done?

**Comment by brentp** [comment]
I just pushed a update the cyvcf2 so the `VCF` constructor can take an integer file descrptor. you can get this from a python filehandle with `fh.fileno()`.
I don't know how to use a bytesIO unless you can get it into a file descriptor.
