### ISSUE TITLE
matplotlib conda requirement

### ISSUE THREAD

**Issue by vladsaveliev** [brentp/cyvcf2#83]
Also pinging @chapmanb as Brad created the package originally: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cyvcf2/meta.yaml

Brad, Brent, as far as I can see, matplotlib for cyvcf2 is quite optional and required only for this plotting function: https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L569

However, the conda package brings the large matplotlib package which pulls an even larger qt library, that is an overkill when you need to build a small tool that needs a VCF parser. Do you think it would make sense to clean up the conda deps e.g. in accordance with the pip requirements? https://github.com/brentp/cyvcf2/blob/master/requirements.txt Then matplotlib then can be offered in the docs, and the code can try-catch `import matplotlib`, and fail gracefully if it's absent.

Super lower priority, just wanted to check if you had any thoughts on that. I know there is a lot of discussions on optional dependencies in conda, e.g. https://github.com/conda/conda/issues/793 and
https://github.com/conda/conda/issues/1696, but it's not quite there yet.

**Comment by brentp** [comment]
I support removing MPL as a required dep as it's only used by peddy which already requires in its own recipe anyway.

**Comment by chapmanb** [comment]
Thanks Vlad for catching this, +1 from me as well. Having a more lightweight cyvcf2 recipe is a good goal.

**Comment by vladsaveliev** [comment]
Fantastic, thanks for the quick replies. In this case I'll remove pandas, seaborn and matplotlib altogether - they all are used only for that one peddy plot.
