### ISSUE TITLE
test_issue44 fails

### ISSUE THREAD

**Issue by LiubovCh** [brentp/cyvcf2#89]
Hi,
I am trying to get the package into the Debian repository. While running tests, I get this error:
```
======================================================================
FAIL: cyvcf2.tests.test_reader.test_issue44
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/package_testing/cyvcf2/cyvcf2/tests/test_reader.py", line 712, in test_issue44
    assert v.genotypes == [expected[i]], (v.genotypes, expected[i])
AssertionError: ([[-1, True]], [-1, False])
    #print(v.genotypes, file=sys.stderr)
>>  assert Variant(2:176938647 A/G).genotypes == [[[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1]], (Variant(2:176938647 A/G).genotypes, [[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1])
```
The same error occurs when I install **cyvcf2** and run the tests as it is recommended in **README.md**

**Comment by LiubovCh** [comment]
Surprisingly, the test does not fail in about one-third of cases...

**Comment by brentp** [comment]
I have updated this test recently but it wasn't tagged in a release. I didn't understand what was causing it (I think an interaction with the nose testing) but I haven't seen the error since then.

I have just now tagged v0.10.0 and uploaded to pypi. would you give that a try?
thanks for getting this into debian! and let me know if the problem persists with the latest version.

**Comment by LiubovCh** [comment]
Thank you for your rapid answer! I tried v0.10.0, but unfortunately, the problem persists.

**Comment by brentp** [comment]
can you share the output of a failing test?

**Comment by LiubovCh** [comment]
Here it is:
```
cyvcf2.tests.test_reader.test_issue44 ... FAIL

======================================================================
FAIL: cyvcf2.tests.test_reader.test_issue44
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/package_testing/cyvcf2-0.10.0/cyvcf2/tests/test_reader.py", line 712, in test_issue44
    assert v.genotypes == [expected[i]], (i, v.genotypes, expected[i])
AssertionError: (1, [[-1, True]], [-1, False])
    #print(v.genotypes, file=sys.stderr)
>>  assert Variant(2:176938647 A/G).genotypes == [[[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1]], (1, Variant(2:176938647 A/G).genotypes, [[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1])
    

----------------------------------------------------------------------
Ran 55 tests in 1.686s
```

**Comment by brentp** [comment]
I have seen this before, but now I'm not able to re-create. 
Can you make sure you have a clean directory with:
```
rm -rf cyvcf2/cyvcf2.so cyvcf2/cyvcf2.c build/ dist/ cyvcf2.egg-info/ cyvcf2/*.pyc
```

and then re-run the tests?
so we can rule out some stale files causing this?

**Comment by LiubovCh** [comment]
Cleaning directory does not help. I guess that the problem is in this piece of code where ploidy and phasing are defined:
```python
 property genotypes:
     def __get__(self):
            ...
            for i in range(n_samples):
              k = i * nret
              for j in range(nret):
                  if bcf_gt_is_missing(gts[k + j]):
                      self._genotypes[i].append(-1)
                      continue
                  if gts[k + j] == bcf_int32_vector_end:
                      break
                  self._genotypes[i].append(bcf_gt_allele(gts[k + j]))
              self._genotypes[i].append(
                    bool(bcf_gt_is_phased(gts[k+1])))
```
Phasing is defined using `k+1`. But in case of `nret` being equal to 1, `k+1` refers to the second (non-existent) column, and hence, leads to random values.

**Comment by brentp** [comment]
thanks for finding this. I have pushed a fix that avoids the out-of-bounds that you note. 
would you mind testing and if that works for you I will tag a new release. I am still not able to trigger this locally.

**Comment by smoe** [comment]
As promised on https://github.com/brentp/cyvcf2/issues/91, after having run into the very same issue I have tested that patch and confirm the package to build and test without error.

**Comment by LiubovCh** [comment]
Hi,
I confirm too that there is no the error now! Just one remark about `cyvcf2/cyvcf2.c`: I think it was mistakenly added to the source since it is not regenerated while building and hinders an up-to-date build.

**Comment by brentp** [comment]
thanks for verifying. I have since removed cyvcf2.c from the source.
