### ISSUE TITLE
can't install on windows 10, python37

### ISSUE THREAD

**Issue by bigmichele** [brentp/cyvcf2#90]
I am hoping to install the package cyvcf2 on my Windows 10 machine. I'm running into compile errors.
Following instructions elsewhere, I installed MSVC version 14.  Then I downloaded the cyvcf2 package (https://pypi.org/project/cyvcf2/#files) and ran "pip install cyvcf2"

Did I get an incompatible set of files?  The compile errors begine here:.
...
    cyvcf2\cyvcf2.c(61119): error C2039: 'exc_type': is not a member of '_ts'
    c:\python37\include\pystate.h(209): note: see declaration of '_ts'
    cyvcf2\cyvcf2.c(61120): error C2039: 'exc_value': is not a member of '_ts'
    c:\python37\include\pystate.h(209): note: see declaration of '_ts'
...
The errors seem valid to me: elsewhere in the .c file, the code uses _ts fields from Pystate.h:
    PyObject *curexc_type;
    PyObject *curexc_value;
but where the error occurs, only "exc_type", etc.
???

**Comment by bigmichele** [comment]
Thanks, but not necessarily a Windows issue.  Do I have the correct files
(attached)?
cyvcf2.c (from the package) includes pystate.h (from python37), but the two
files are not compatible.  Which is incorrect?

**Comment by nkrumm** [comment]
I am having a (?) similar problem with Mac 10.13.5 + Python 3.7.0.

`pip install cyvcf2` fails with numerous clang warnings and errors and then:
```

    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    30 warnings and 20 errors generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/Users/nkrumm/.virtualenvs/ddcfdna/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/l6/m8f_znt12l1c1byrqhg27jkc0000gp/T/pip-install-7qwc3dnj/cyvcf2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/l6/m8f_znt12l1c1byrqhg27jkc0000gp/T/pip-record-345i6zt6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/nkrumm/.virtualenvs/ddcfdna/bin/../include/site/python3.7/cyvcf2" failed with error code 1 in /private/var/folders/l6/m8f_znt12l1c1byrqhg27jkc0000gp/T/pip-install-7qwc3dnj/cyvcf2/
```

Seems like a Cython/Python3.7 issue, but reporting here for now.

**Comment by muppetjones** [comment]
Similar issue on latest OSX as @nkrumm, @brentp :
```
    /path/python3.7m/pystate.h:237:15: note: 'curexc_value' declared here
        PyObject *curexc_value;
                  ^
    cyvcf2/cyvcf2.c:61181:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tmp_tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
    /path/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    30 warnings and 20 errors generated.
    error: command 'clang' failed with exit status 1
```

**Comment by owainkenwayucl** [comment]
This is a problem that has shown up in other packages - basically Python 3.7.x changes some of the interfaces Cython generated code calls, which breaks packages with old generated cython code.

You need to update Python + Cython and regenerate the code.

**Comment by dridk** [comment]
In my experience, htslib only compiles using mingw. So, in theory, cyvcf2 should work if you use the python version from msys2. But it didn't . Same for pysam .

**Comment by Zilong-Li** [comment]
For people who had a hard time working with the VCF on windows, I made a R package for rapid manipulation of the VCF (https://github.com/Zilong-Li/vcfppR/blob/main/tests/testthat/test-vcf-reader.R). Hope you find it helpful.

**Comment by brentp** [comment]
this should be fixed with latest version of cyvcf2
