### ISSUE TITLE
question: reading vcf files from S3

### ISSUE THREAD

**Issue by matthdsm** [brentp/cyvcf2#96]
Hi,

Is it possible to read/parse vcf files stored on an S3 server using cyvcf2?
If so, would it be possible to elaborate a bit?

Thanks
M

**Comment by matthdsm** [comment]
Hi,

After quickly checking the HTSlib docs, I suppose a conda installed `cyvcf2` *should* be able to read from S3. The recipe uses this build cmd
```
./configure --prefix=${PREFIX} --enable-libcurl --with-libdeflate --enable-plugins --enable-gcs --enable-s3
```
which included all the required moving parts.

Any pointers on how to get this to work in practice? I've tried passing an `HTTPstream` and a presigned URL, but with no luck. And even if those would work, I don't thing we'd get any output since I didn't find any options to pass a `tbi` index path.

If you've got the the time, could you expand the docs a bit? Looking through the code, `cyvcf2` seems extremely powerful and versatile, and I'm afraid I'm missing out on some seriously awesome functionality.

Cheers
M

**Comment by brentp** [comment]
Well, a good start would be to find a project that uses an existing shared library. (I think pysam has an option for this) and then see how they do that in the setup.py. It would be ideal to use an already install libhts.so if it was available and use the current setup if not.

if you list the things that are not documented, I will add them to the docs.

**Comment by matthdsm** [comment]
Hi Brent,

I think using an existing htslib shouldn't be that complicated. The setup.py from pysam as you suggested is pretty clear, as are the [docs](https://pysam.readthedocs.io/en/latest/installation.html#external) and [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pysam/meta.yaml).

I'll have a look if I can whip something up.
Cheers
M

**Comment by matthdsm** [comment]
As for the docs,  it would be great to have a list exposed methods and variables for the VCF and variant objects. I know I can go look those up in the code, but it would be nice for me (and other users) to have a comprehensive list of what cyvcf2 is able to output.

Cheers
M

**Comment by matthdsm** [comment]
Seems fixed with the htslib update. Closing

Thanks to everyone involved.
